= Allowlisting Trusted Domains in Anypoint Platform

Register trusted domains to allow HTTP requests to external resources through the API Console proxy. Anypoint Platform requires domain registration before making secure calls to third-party services.

== Add a New Trusted Domain

The new domain must not duplicate an existing trusted domain and can't be a MuleSoft or Anypoint Platform domain or subdomain.

include::partial$include-nav-steps-org-admin.adoc[]

. Click *Trusted domains*.
. Click *Add domain*. 
. In the dialog box, enter the domain name and click *Add domain*. 
+
You are redirected to the Trusted Domains page, where you can edit or delete domains. If you register a domain on a parent organization, it's also allowlisted on all business groups.

[[auto-registration-domains]]
== Automatic Registration of Domains

Some domains are added automatically:

* Publishing an API specification to Exchange adds the implementation base URI.
* Sending a request through the proxy adds the implementation base URI.
* Unauthenticated requests from public Exchange portals or Mocking Service shareable links are added.

NOTE: Public Anypoint Exchange assets and portals created before 2024 might not auto-register. Manually register those domains. 


== See Also

* xref:managing-ip-allowlists.adoc[]
* xref:managing-security-settings.adoc[]
* xref:managing-your-account.adoc#allowlist-urls[Allowlist URLs to Sign in to and Use Anypoint Platform]