= Configure Audit Log Retention in Access Management

Control how long audit logs are kept to meet compliance and storage requirements. New organizations default to one year. Organizations created before July 10, 2023, default to six years unless changed. Users with *Audit Log Config Manager* and *Organization Administrator* permissions can configure retention in Access Management.

Download your logs periodically to maintain your log files for longer than six years.
To find your organization's audit log retention period, view the retention setting in your root organization's settings, or use the https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/audit-log-query-api/minor/1.0/console/method/%23341/[Audit Logging API^].

When you configure a retention period:

* You can specify a retention period between 30 and 2190 days.
* The date the new retention period takes effect must be a minimum of seven days from the current date.
* Configuring a new retention period affects your organization's compliance policy.

[[before-you-begin]]
== Before You Begin

Before getting started, make sure your account has these permissions:

* *Audit Log Config Manager*
* *Organization Administrator* (required only if you're using the user interface to set retention. You don't need this permission if you're using the API.)

Your organization must also have *Try new features* or the Teams feature enabled in Access Management. 

[[configure-audit-log-retention]]
== Configure Audit Log Retention Period

include::partial$include-nav-steps-org-admin-audit-log-mgr.adoc[]

. Click the *Settings* tab.
. Next to *Audit Log Retention Period*, click the pencil icon.
. In the *Days* field, enter a value between 30 and 2190.
. In the *Date Effective* field, select the date to start the new retention period on.
. Click *Save Changes*. +
A warning appears, confirming your new retention period and effective date.
+
. Click *Confirm*. +
The new audit log retention period takes effect on the date you specified at 00:00:00 UTC. 

== See Also

* xref:audit-logging.adoc[]
* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/audit-log-query-api/minor/1.0/console/method/%23343/[Audit Logging API^]
