= Connected Apps
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Connected Apps feature provides a framework that enables an external application to integrate with Anypoint Platform using https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/[APIs] through OAuth 2.0 and OpenID Connect.
Connected apps help users delegate their access without sharing sensitive credentials or giving full control of their accounts to third parties.
Actions taken by connected apps are audited, and users can also revoke access at any time.
Note that some products do not currently include client IDs in this release of the Connected Apps feature.
The Connected Apps feature enables you to use secure authentication protocols and control an app's access to user data. Additionally, end users can authorize the app to access their Anypoint Platform data.

== Authentication

Anypoint Platform supports OAuth 2.0 and OpenID Connect to authorize apps to access data within Anypoint Platform.
OAuth (Open Authorization) is an open protocol that provides secure API authorization from applications in a simple and standardized way.
OAuth 2.0 can authorize access to resources without revealing user credentials to apps.
OpenID Connect identifies the end user and obtains information to pass to OAuth 2.0 connected apps.



The Connected Apps feature implements OAuth 2.0 and OpenID Connect, or _OIDC_, for authorizing access to data. OAuth 2.0 and OpenID Connect flows grant permission to services and users to access the Anypoint APIs.

=== OAuth 2.0

The OAuth 2.0 authorization protocol depends on several elements to function. 

Client::
The resource that requests data on behalf of a user or service.

Authorization server::
The server that gives access tokens to the client once it does authorization.

Resource server::
The system that contains the requested data.

Access token:: 
A "key" needed to access data in the resource server. 

Redirect URI::
The destination the authorization server sends the user or server once the application is authorized.

There are many types of OAuth 2.0 flows; Connected Apps uses the following:

`authorization_code`:: 
In the authorization_code flow, the client navigates to the authorization server. The server then requests authorization for specific scopes, or _permissions_, from the user. If the user authorizes the client to have this information, an authorization code is sent the redirect URI. The redirect URI then exchanges the authorization code for an access token from the authorization server. The access token is then sent to the resource server to obtain the data by means of a specific API. This flow demonstrates _an application acting on behalf of the user_.

`client_credentials`::
In the client_credentials flow, the client navigates to the authorization server. The server then requests authorization for specific scopes, or _permissions_, from the application. If the application authorizes the client to have this information, an authorization code is sent the redirect URI. The redirect URI then exchanges the authorization code for an access token from the authorization server. The access token is then sent to the resource server to obtain the data by talking to a specific API. This flow demonstrates a _service-to-service_ use case.


=== OpenID Connect (OIDC)

OICD is an authentication protocol that authenticates users. This identity layer complements OAuth 2.0 protocol and provides authentication at a layer above it.


For more information, see https://oauth.net/2/[OAuth 2.0] and https://openid.net/connect/[OpenID Connect].

== Access and Authorization

You can use the Connected Apps feature to create a seamless authentication experience for end users. Connected apps address use cases for the following types of users:

* An xref:connected-apps-org-admin.adoc[organization administrator] can control how their organization’s data is used by whitelisting apps, revoking access, and disabling this feature for the entire organization.
* An xref:connected-apps-developers.adoc#developers[organization administrator who is developing a connected app] can register new (and manage existing) apps within their organization.
* An xref:connected-apps-end-users.adoc#end-users[end user] can authorize apps to access particular information, such as viewing assets in Anypoint Exchange.
