= Connected Apps
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Connected Apps feature provides a framework that enables an external application to integrate with Anypoint Platform using https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/[APIs] through standard protocols, such as SAML, OAuth 2.0, and OpenID Connect.
Connected apps help users delegate their access without sharing sensitive credentials or giving full control of their accounts to third parties.
Actions taken by connected apps are audited, and users can also revoke access at any time.
Note that some products do not currently include client IDs in this release of the Connected Apps feature.
The Connected Apps feature enables you to use secure authentication protocols and control an app's access to user data. Additionally, end users can authorize the app to access their Anypoint Platform data.

== Authentication

Anypoint Platform supports OAuth 2.0 and OpenID Connect to authorize apps to access data within Anypoint Platform.
OAuth (Open Authorization) is an open protocol that provides secure API authorization from applications in a simple and standardized way.
OAuth can authorize access to resources without revealing user credentials to apps.
OpenID Connect identifies the end user and obtains information to pass to OAuth 2.0 connected apps.

For more information, see https://oauth.net/2/[OAuth 2.0] and https://openid.net/connect/[OpenID Connect].

== Access and Authorization

You can use the Connected Apps feature to create a seamless authentication experience for end users. Connected apps address use cases for the following types of users:

* An xref:connected-apps-org-admin.adoc[organization administrator] can control how their organization’s data is used by whitelisting apps, revoking access, and disabling this feature for the entire organization.
* A xref:connected-apps-developers.adoc#developers[developer] can register new, and manage existing, apps within their organization.
* An xref:connected-apps-end-users.adoc#end-users[end user] can authorize apps to access particular information, such as viewing assets in Anypoint Exchange.
