= Connect a Trusted Salesforce Organization to Anypoint Platform

Establish a tenant relationship between your Anypoint Platform organization and a trusted Salesforce organization to enable secure data sharing and centralized capability management. The connection uses two tenant keys (one from each organization) and involves the Anypoint Platform organization administrator and the Salesforce organization administrator. Depending on whether one person holds both roles or two people split the roles, follow the appropriate scenario.

Ways to establish a tenant relationship include:

* A Salesforce organization is provisioned with the tenant relationship to an Anypoint Platform organization established. In this case, the Anypoint Platform organization administrator only needs to xref:managing-connected-salesforce-orgs.adoc#enable-disable-connection[enable the existing connection] in Anypoint Platform.
* The Anypoint Platform organization administrator initiates the tenant relationship in Anypoint Platform and the Salesforce organization administrator completes the setup in Salesforce.

== Before You Begin

* Anypoint Platform organization administrators must have the *Organization Administrator* permission at the root organization level
* Salesforce organization administrators must have the *System Administrator* user profile.

== Choose Your Scenario

Pick the path that matches who is doing the work.

=== One Person Manages Both Organizations

If you are the organization administrator for both the Anypoint Platform and Salesforce organizations:

. Start in Salesforce by <<get-salesforce-tenant-key,getting the Salesforce organization tenant key>>.
. In Anypoint Platform, <<connect-orgs,connect with a Salesforce organization>>.
. In Salesforce, <<complete-organization-connection,complete the organization connection process>>.

=== Different People Manage the Organizations

If different people manage the Anypoint Platform and Salesforce organizations:

. The Salesforce organization administrator <<get-salesforce-tenant-key,gets the Salesforce organization tenant key>> and shares it with the Anypoint Platform organization administrator.
. The Anypoint Platform organization administrator uses the Salesforce organization's tenant key to <<connect-orgs,connect with a Salesforce organization in Anypoint Platform>>, and then copies the Anypoint Platform organization key and shares it with the Salesforce organization administrator.
. The Salesforce organization administrator <<complete-organization-connection,completes the connection in Salesforce>> using the Anypoint Platform organization key.

[[get-salesforce-tenant-key]]
== Get the Salesforce Organization Tenant Key
Role: Salesforce organization administrator

include::partial$include-salesforce-mulesoft-setup-nav.adoc[]

. In *Your connected Anypoint Platform Organization*, click *Complete the Connection*.
. In *Connection to MuleSoft Anypoint Platform*, copy the Salesforce organization tenant key.
. If you are signed in to the Salesforce organization as an admin, click *Go to Anypoint Platform*. 
. Select the region for your Anypoint Platform organization and click *Go to Anypoint Platform*.
. Sign in to Anypoint Platform using an account that has the root Organization Administrator permission and continue to <<connect-orgs,Connect With a Salesforce Organization in Anypoint Platform>>.

[[connect-orgs]]
== Connect with a Salesforce Organization in Anypoint Platform
Role: Anypoint Platform organization administrator

Start the process of connecting to a trusted Salesforce organization in Anypoint Platform. 

You must have the Salesforce organization's connection key (tenant key) before you can connect to a Salesforce organization. Contact the Salesforce organization admin to get the tenant key. 

include::partial$include-nav-salesforce.adoc[]

. Click *Add Salesforce Org*.
. Enter the Salesforce organization's tenant key, and click *Confirm*. 
+
The format for the Salesforce tenant key is `cloud/env/org-id`.
. In *Add the Salesforce Org*, verify the information and click *Add*. 
+
Anypoint Platform generates and provides the organization key (or tenant key) in the format `cloud/env/org-id`.
. Click *Copy* to copy the Anypoint Platform organization key. 
+
To complete the connection process, the Salesforce organization administrator enters this organization key (or tenant key) into the Salesforce organization you are connecting to in Salesforce.
. If you are the admin for the Salesforce organization you are adding, click *Manage in Salesforce* to continue setting up the relationship in Salesforce. 
+
If you are not the Salesforce admin, provide the Anypoint Platform organization key to the Salesforce admin so they can finish the connection process in Salesforce.

When the connection process is complete, the Salesforce organization appears in the *Salesforce Orgs* section of the *Salesforce* page.

[[complete-organization-connection]]
== Complete the Organization Connection in Salesforce
Role: Salesforce organization administrator

Complete the connection between your organization and the Anypoint Platform organization after the connection process is initiated in Anypoint Platform. You must have the Anypoint Platform organization (tenant) key to complete the connection.

include::partial$include-salesforce-mulesoft-setup-nav.adoc[]

. In *Your connected Anypoint Platform Organization*, click *Complete the Connection*.
. In *Connection to MuleSoft Anypoint Platform*, enter the Anypoint Platform organization key in *Anypoint Platform Organization ID*, and then click *Connect*.
+
The format for the Anypoint Platform organization key is `cloud/env/org-id`. 
+ 
If you don't have the Anypoint Platform organization key, contact the Anypoint Platform organization administrator.
+ 
You return to the *Connection to MuleSoft Anypoint Platform* page. The page shows the connected Anypoint Platform organization details, including the enablement status of the capabilities associated with your Salesforce organization. 

== See Also

* xref:trusted-salesforce-org.adoc[]
* xref:managing-connected-salesforce-orgs.adoc[]
