= Connected Apps
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can delegate user access to a client app without granting it unrestricted access to data or having to share sensitive credentials.
When you grant an app access, you have direct control over its data access and usage.
You can audit the use of data and actions taken by connected apps, and you can also revoke access at any time.

== Authentication

You can use OAuth 2.0 and OpenID Connect to authorize apps to access resources.

For more information on using OAuth 2.0 and OpenID Connect, see https://openid.net/connect/[OpenID Connect].

== Access and Authorization

Different types of users can interact can connect apps or manage authorization in various ways:

* An Organization Administrator can control how their organization's data is used by connected apps.
* A developer can register and administrate an app that they have created.
* An end user can authorize an app to use their credentials.

// will add links to the persona pages for each of those lines.
