= Connected Apps for Developers

Leverage Anypoint Platform APIs securely by developing or using connected apps. Understand how connected apps use OAuth 2.0 and OpenID Connect to delegate access, enabling interactions like building CI/CD pipelines or integrating third-party services without exposing user credentials. Learn about authentication flows, token usage, and considerations like application allowlisting from a developer's perspective.

The Connected Apps feature enables you to:

* Delegate access to applications that use APIs to interact with Anypoint Platform programmatically. 
* Build CI/CD pipelines or productize additional third-party use cases on top of Anypoint Platform.
* Enable or disable clients and view client usage. For example, you can see how many organizations are using the app and how many users have access.

== Authentication

The Connected Apps feature supports OAuth 2.0 and OpenID Connect, so you must ensure your app can use tokens to request access to user data.

See the information in the Open ID configuration https://anypoint.mulesoft.com/accounts/api/v2/oauth2/.well-known/openid-configuration[discovery endpoint] to find the supported OpenID Connect capabilities. 

To make the authentication experience consistent for end users, third-party developers with their own websites or web apps can allow users to sign in using the *Sign in with Anypoint Platform* option.


[[application-allowlist-dev]]
== Application Allowlist

Organization administrators can enable an allowlist to control which apps can access the organization's user data.

When your app is added to an allowlist, only the set of scopes associated with the app are reviewed and approved by the administrator. If you add new scopes to your app later, you're unable to request those scopes from users until the admin reapproves your app.
Existing authorizations and new authorizations using the previously allowlisted set of scopes continue to work.

For more information, see xref:connected-apps-org-admin.adoc#application-allowlist-admin[connected apps for administrators].

== See Also

* https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/access-management-api/minor/1.0/pages/Connected%20App%20Examples/[Access Management API - Connected App Examples]
* xref:creating-connected-apps-dev.adoc[]
* xref:connected-apps-org-admin.adoc[]