= Connect a Trusted Salesforce Organization to Anypoint Platform

Establish a tenant relationship between your Anypoint Platform organization and a trusted Salesforce organization to enable secure data sharing. Initiate the connection in Anypoint Platform and complete it in Salesforce using organization keys. After linking, you can manage capabilities and verify the connected organization details.

Ways to establish a tenant relationship include:

* A Salesforce organization is provisioned with the tenant relationship with an Anypoint Platform organization already established. In this case, the Anypoint Platform organization administrator just needs to xref:managing-connected-salesforce-orgs.adoc#enable-disable-connection[enable the connection] in Anypoint Platform. 
* The Anypoint Platform organization administrator initiates the tenant relationship in Anypoint Platform and the Salesforce organization administrator completes the setup in the Salesforce organization.   

In some cases, the Anypoint Platform organization administrator and Salesforce organization administrator are different people, and in some cases, they are the same person.

== Before You Begin

* Anypoint Platform organization administrators must have the *Organization Administrator* permission at the root organization level
* Salesforce organization administrators must have the Salesforce administrator permission set.

[[get-salesforce-tenant-key]]
== Get the Salesforce Organization Tenant Key

include::partial$include-salesforce-mulesoft-setup-nav.adoc[]

. In *Your connected Anypoint Platform Organization*, click *Complete the Connection*.
. In *Connection to MuleSoft Anypoint Platform*, copy the Salesforce org tenant key.
. If you are signed in to the Salesforce organization as an admin, click *Go to Anypoint Platform*. 
. Select the region for your Anypoint Platform organization and click *Go to Anypoint Platform*.
. Sign in to Anypoint Platform using an account that has the root Organization Administrator permission and continue to <<connect-orgs,Connect With a Salesforce Org in Anypoint Platform>>.

[[connect-orgs]]
== Connect With a Salesforce Org in Anypoint Platform

As an Anypoint Platform organization administrator, you can start the process of connecting to a trusted Salesforce organization. 

You must have the Salesforce organization's connection key (tenant key) before you can connect to a Salesforce organization. Contact the Salesforce organization admin to get the tenant key. 

include::partial$include-nav-salesforce.adoc[]

. Click *Add Salesforce Org*.
. Enter the Salesforce organization's tenant key, and click *Confirm*. 
+
The format for the Salesforce tenant key is `cloud/env/org-id`.
. In *Add the Salesforce Org*, verify the information and click *Add*. 
. Click *Copy* to copy the Anypoint Platform organization key. 
. If you are the admin for the Salesforce organization you are adding, click *Manage in Salesforce* to continue setting up the relationship in Salesforce. 
+
If you are not the Salesforce admin, provide the Anypoint Platform organization key to the Salesforce admin so they can finish the connection process in Salesforce.

When the connection process is complete, the Salesforce organization appears in the *Salesforce Orgs* section of the *Salesforce* page.

[[complete-organization-connection]]
== Complete the Organization Connection in Salesforce

As a Salesforce organization administrator, you complete the connection between your organization and the Anypoint Platform organization when the connection process is initiated in Anypoint Platform. You must have the Anypoint Platform organization (tenant) key to complete the connection.

include::partial$include-salesforce-mulesoft-setup-nav.adoc[]

. In *Your connected Anypoint Platform Organization*, click *Complete the Connection*.
. In *Connection to MuleSoft Anypoint Platform*, enter the Anypoint Platform organization key in *Anypoint Platform Organization ID*, and then click *Connect*.
+
The format for the Anypoint Platform organization key is `cloud/env/org-id`. 
+ 
If you don't have the Anypoint Platform organization key, contact the Anypoint Platform organization administrator.
+ 
You return to the *Connection to MuleSoft Anypoint Platform* page. The page shows the connected Anypoint Platform organization details, including the enablement status of the capabilities associated with your Salesforce organization. 

== See Also

* xref:trusted-salesforce-org.adoc[]
* xref:managing-connected-salesforce-orgs.adoc[]
