= Connected Apps Permissions by User
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Connected Apps can be used by organization administrators, developers, and end users.
and there are some restrictions to ensure sensitive data remains secure.

== Organization Administrator

Organization administrators are the only users that can view and manage connected apps in Access Management.

To manage your connected apps, navigate to Access Management and select the *Applications* tab.

// screenshot of Connected Apps page

The *Connected Apps* page shows a list of apps that are connected to Anypoint Platform.
To add an application, select *Add Application*.

=== Create an App

When you create an app as an organization administrator, consider the below:

* An organization can own up to 200 connected apps.
* You can disable or whitelist connected apps.
* When you create an app, a unique clientID is assigned; the clientID can't be modified. However, you can modify client secrets in the *Application Settings* page.
* When you create an application with the OAuth client credential grant type, the app is owned by the organization; any organization administrator can control the app.
* For apps that use the user grant type, actions taken by the app are logged with an application ID and user ID in the audit log so administrators can monitor and audit data use.

// screenshot of Create Application interface

When creating an application, you must enter the below information:

* *Application Name*:

 A descriptive name for your application.

* *Redirect URIs*:

 Uniform Resource Identifier that specifies the location of the application's callback. You can specify one per line.

* *Allowed Grant Types*: 

 A list of OAuth 2.0 grant types the application intends to make use of. It is important to specify the access permissions when connecting an app since that will dictate the available grant types. Note that client grant types are only available for private, first-party apps. 

==== User Grants

Clients making use of user grant types require authorization from a user. Connected Apps currently supports two methods of receiving authorization.

* Browser-based Authorization Flow:

 The app directs the user's browser (commonly called a User-Agent) to Anypoint, where the user authorizes the app before being redirected back. If the code should not work indefinitely, you can select the *Refresh Tokens* option, requiring new codes as often as specified in the application.

* JWT Bearer:

 A private app that the organization administrator registers with a public key. The app uses the corresponding private key to sign JWTs that may then be exchanged for an access token. 

You can specify the list of scopes the app is allowed to request from a user after you select one or more user grant types.

==== Client Grants

Client grants give users access based on their organizational affiliations and are permitted only for first-party apps.
You can also specify which environments the app can access.

You can specify the list of scopes the app is allowed to request from a user after you select an organization or organization and environment.

== Developer

Developers who have websites or web apps can allow users to log in using the *Log in with Anypoint Platform* option.
For this feature to work, the connected application must be configured with user grant authentication.

// code/chunk of steps for websites/web apps

== End User

An end user can log into a connected application using their Anypoint credentials. End users can also  authorize access when the following message appears:

// screenshot of authorize user page https://qax.anypoint.mulesoft.com/login/authorize?state=eyJjbGllbnQiOnsiY2xpZW50X2lkIjoiZWEzYzJiODFkMDEyNGI0Mjk1NDYyM2RhMWM0MzQ5ZWIifSwidXNlciI6eyJ1c2VybmFtZSI6Im9yZ2FuaXphdGlvbl9vd25lciJ9LCJvcmlnaW4iOiIvYXBpL3YyL29hdXRoMi9hdXRob3JpemU%2FY2xpZW50X2lkPWVhM2MyYjgxZDAxMjRiNDI5NTQ2MjNkYTFjNDM0OWViJnJlZGlyZWN0X3VyaT1odHRwczovL2V4YW1wbGUuY29tJnJlc3BvbnNlX3R5cGU9dG9rZW4mc2NvcGU9ZnVsbCIsInRyYW5zYWN0aW9uX2lkIjoiSXlNVGVJSHciLCJzY29wZSI6WyJmdWxsIl19

End users can manage third-party applications to which they have access in their profile settings.
