= Enabling Integration Intelligence

Integration Intelligence enhances monitoring, analysis, and troubleshooting of MuleSoft integrations through AI-powered capabilities.

Integration Intelligence gives you:

* AI-driven actionable insights, smarter monitoring, and proactive operations. It helps you efficiently monitor, analyze, and troubleshoot data using AI-powered Natural Language Processing (NLP). This streamlines operations with quick insights and automated actions.
* Accelerated troubleshooting by enabling the pinpointing of root causes using NLP over telemetry data, reducing the need for manual queries.
* Enhanced visibility across Salesforce including tracing call chains across Flows, Mule apps, Large Language Models (LLMs), and capabilities beyond traditional Anypoint Monitoring.
* Proactive real-time intelligence by using the real-time streaming capabilities of Data Cloud, entity profiles, and AI-driven insights to facilitate automated, smarter actions.
* Seamless observability with AI agents, letting you view AI-driven dashboards in Tableau Next.
* Improved monitoring with pre-built dashboards that display performance and usage metrics for all applications and APIs in a single location. You can also create custom dashboards tailored to your specific business needs. 
* Troubleshooting assistance and insights with AI agents. 

== Before you begin

Before enabling Integration Intelligence in your Anypoint Platform organization, you must:

* Have administrative access to an Anypoint Platform organization that isn't a trial organization and isn't expired.
* Have an Anypoint Platform organization that is linked to a Salesforce organization with a connected Data Cloud instance. 
* Have administrative access to a Salesforce organization that has Integration Intelligence enabled.

== Enable Integration Intelligence in Anypoint Platform

This feature is enabled in Anypoint Platform, not directly in Salesforce. The ability to turn on this feature is governed by the Integration Intelligence opt-in switch in Salesforce.

include::partial$include-nav-steps-org-admin.adoc[]

. Select *Salesforce*.
. Enable *Ingest Telemetry Data*.
. Opt in to ingest telemetry data by selecting *I understand and agree to join the Beta program*.
. In *Initial Ingestion*, select the time period for historical data ingestion. 
. In *Business Group*, select one business group whose telemetry data will be brought to Data Cloud.
. Select *Save Settings*.

Any subsequent changes made to Integration Intelligence in Access Management (for example, disabling trust or changing business groups) are automatically shared with the connected Salesforce organization.

== Enable Seamless Sign-On for Anypoint PlatformUsers

Seamless sign-on lets Anypoint Platform users access Tableau Next dashboards in Salesforce without needing to create new credentials or perform additional login steps. 



== Enable Integration Intelligence in Salesforce

