= Enabling API Catalog

Enable a connected Salesforce organization to access and import Anypoint Platform APIs into the Salesforce API Catalog and expose them as invocable actions. This capability is enabled in Anypoint Platform access management by an Anypoint Platform organization administrator.


== Enable API Catalog in Anypoint Platform

To enable this feature:

include::partial$include-nav-steps-org-admin.adoc[]

. Click *Salesforce*.
. In the *Capabilities Managed in Anypoint Platform* section, click *Settings* next to *Make MuleSoft Anypoint Platform APIs Available in Salesforce*.
. In *Settings for Anypoint APIs in Salesforce*, click *Continue*.
. In the *Settings* page, select the Anypoint Platform business groups that allow the selected Salesforce org to import Anypoint Platform APIs into its API Catalog, and click *Save Settings*.
+
[NOTE]
Within the selected business groups, only APIs that have specs published in Exchange with active instances can be imported into the Salesforce organization.
. In the next window, select which APIs to make available to the connected Salesforce organization, and then click *Save settings*.
. In the *Capabilities Managed in Anypoint Platform* section, turn on the *Make MuleSoft Anypoint Platform APIs Available in Salesforce* feature. 
. The Salesforce organization administrator must then turn on synchronization to import the APIs into their catalog.
. After the APIs are imported, the Salesforce administrator selects individual API instances and operations and converts them into invocable actions for access by selected Salesforce developers.
. A client ID is created and an access request for the selected Salesforce developers is sent to the Anypoint Platform owner of that API through API Manager.
+
Only after the request is accepted can those selected Salesforce developers start using the API.
+
After the Salesforce organization imports APIs from Anypoint Platform into its API Catalog, changes to the settings in Anypoint Platform affect synchronization with the Catalog. Access granted to Anypoint Platform APIs continues through API Manager, but the API Catalog might not have the latest versions of the APIs from Anypoint Platform.

== See Also

* xref:trusted-salesforce-org.adoc[]
* LINK TO API CATALOG documentation
* xref:managing-connected-salesforce-orgs.adoc[]