= External Organization Access

The External Access feature enables separate organizations to collaborate in Anypoint Platform. For example, organizations can share API specifications, connectors, and other assets in Anypoint Exchange with each other, without making them public. Additionally, you can establish a connection with a trusted Salesforce organization.

Anypoint Platform organization administrators control which organizations their users can collaborate with by maintaining a list of trusted organizations in Access Management. Adding an entry to this list means that you trust the other organization and its users, and you acknowledge that you are enabling your users to grant permission to and be granted permissions by the other organization.

Using the External Access functionality in Access Management, you can:

* xref:trusted-anypoint-platform-org.adoc[Establish a relationship with a trusted Anypoint Platform organization.]
* xref:trusted-salesforce-org.adoc[Establish a relationship with a trusted Salesforce organization.]