= Anypoint Platform External Organization Access

External organization access in Anypoint Platform lets separate organizations collaborate by sharing assets in Anypoint Exchange without making them public. Organization administrators control which organizations their users can collaborate with by maintaining a list of trusted organizations in Access Management.

Anypoint Platform organization administrators control which organizations their users can collaborate with by maintaining a list of trusted organizations in Access Management. Adding an entry to this list means that you trust the other organization and its users, and you acknowledge that you're enabling your users to grant permission to and be granted permissions by the other organization.

Using the External Access functionality in Access Management, you can:

* xref:trusted-anypoint-platform-org.adoc[Establish a relationship with a trusted Anypoint Platform organization.]
* xref:trusted-salesforce-org.adoc[Establish a relationship with a trusted Salesforce organization.]