= About Anypoint Access Management
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint platform, permissions, configuring

Use *Access Manager* to xref:managing-your-account.adoc#how-to-create-your-account[create your Anypoint Platform account] or configure federated xref:external-identity.adoc[External Identity].

[TIP]
--
Account creation and user invitation from the platform is not available for Anypoint Platform Private Cloud Edition.
Users running Anypoint Platform Private Cloud Edition need to define a method to xref:external-identity.adoc#managing-users[manage users]. +
--

Additionally, you can configure access and permissions within your xref:organization.adoc[Organization] and, based on your access level, manage the xref:users.adoc[Users] and xref:roles.adoc[Roles].

[NOTE]
As of November 2014, accounts in both the Anypoint Platform for APIs and CloudHub have been merged. For more information about what this merging of accounts implies and how it's being handled, read Upcoming Changes to Anypoint Platform Accounts.

If you have any questions about your account, contact your MuleSoft Account Team for assistance.

Anypoint Access Management also provides a REST API for you to programmatically access the resources related to user and client management, organizations and business groups, and roles and permissions.
Check the https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/11270/versions/11646/pages/11244[Access Management API Portal].
