= About Anypoint Access Management
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint platform, permissions, configuring

Access Management enables you to xref:managing-your-account.adoc#how-to-create-your-account[create your Anypoint Platform account] and configure your user profile. 

For organization owners and administrators, Access Management enables you to:

* xref:users.adoc[Invite users] to your organization and manage their access
* Create xref:business-groups.adoc[business groups] to contain your Anypoint Platform resources such as apps and APIs
* Create xref:environments.adoc[environments] to manage app and API deployment
* xref:managing-permissions.adoc[Assign permissions to individual users] or setup hierarchal user management using the xref:teams.adoc[Teams] feature to manage access to assets and areas of your organization
* Manage user identity and configure single sign-on (SSO) federated xref:external-identity.adoc[external identity providers (IdPs)]
* Protect your organization from unauthorized access using xref:multi-factor-authentication.adoc[multi-factor authentication]
* Authorize client applications xref:managing-api-clients.adoc[external client providers]
* View user and connected app activity using xref:audit-logs.adoc[audit logs]
* Develop and configure xref:connected-apps-overview.adoc[connected apps] to delegate access to the platform
* Allow xref:external-organization-access.adoc[external organization access] to collaborate with other Anypoint Platform organizations

Access Management also provides a REST API for you to programmatically access the resources related to user and client management, organizations and business groups, and roles and permissions.
Check the https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/11270/versions/11646/pages/11244[Access Management API Portal].

Depending on your xref:hosting::hosting-home.adoc[control plane], some Access Management features may be unavailable to your organization. For example, account creation and user invitation from the platform is not available for Anypoint Platform Private Cloud Edition. Certain features are also unavailable for Mulesoft Government Cloud.

If you are an organization administrator and have any questions about your account, contact your MuleSoft Account Team for help. Otherwise, contact your organization administrator.


[NOTE]
As of November 2014, accounts in both the Anypoint Platform for APIs and CloudHub have been merged. For more information about what this merging of accounts implies and how it's being handled, read Upcoming Changes to Anypoint Platform Accounts.




////
Use *Anypoint Access Management* to xref:managing-your-account.adoc#how-to-create-your-account[create your Anypoint Platform account] or configure federated xref:external-identity.adoc[External Identity].

[TIP]
--
Account creation and user invitation from the platform is not available for Anypoint Platform Private Cloud Edition.
Users running Anypoint Platform Private Cloud Edition need to define a method to xref:external-identity.adoc#managing-users[manage users]. +
--

Additionally, you can configure access and permissions within your xref:organization.adoc[Organization] and, based on your access level, manage the xref:users.adoc[users] and xref:teams.adoc[teams].

[NOTE]
As of November 2014, accounts in both the Anypoint Platform for APIs and CloudHub have been merged. For more information about what this merging of accounts implies and how it's being handled, read Upcoming Changes to Anypoint Platform Accounts.

If you have any questions about your account, contact your MuleSoft Account Team for assistance.

Anypoint Access Management also provides a REST API for you to programmatically access the resources related to user and client management, organizations and business groups, and roles and permissions.
Check the https://anypoint.mulesoft.com/apiplatform/anypoint-platform/#/portals/organizations/68ef9520-24e9-4cf2-b2f5-620025690913/apis/11270/versions/11646/pages/11244[Access Management API Portal].
////
