= About Client Management
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This topic provides an overview of client management on Anypoint Platform. As an API owner, you can apply an OAuth 2.0 policy to authenticate client applications that try to access your API. You need an OAuth 2.0 provider to use an OAuth 2.0 policy.

You can configure more than one client provider and xref:environments.adoc#add-an-idp-to-an-existing-environment[associate the client providers with different environments].
When you delete a client provider from your master organization, the client provider is no longer available in environments that used it, and assets that depended on the client provider may break.

You can configure the following OAuth providers:

* xref:conf-client-mgmt-openam-task.adoc[OpenAM version: 14]
* xref:conf-client-mgmt-pf-task.adoc[PingFederate versions: 6 - 8]
* xref:configure-client-management-openid-task.adoc[Dynamic Client Registration-compliant identity providers]
+
This provider needs to conform to the https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Client Registration 1.0 incorporating errata set 1].

To configure client management on Anypoint Platform for these providers, you must have an IdP account.

== Delete a Client Provider

[WARNING]
Prior to deleting a client provider, ensure you do not have assets or environments that depend on the client provider. Any APIs that depend on the client provider break.

. Sign in to Anypoint Platform using an account that has the organization administrator role.
. In Anypoint Platform, click *Access Management*.
. In the menu on the left, click *Client Providers*.
. Click the client provider you want to delete.
. In the client provider's page, click *Delete*.
. Enter the name of the client identity provider name.
. Click *Delete*.

== See Also

* https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Client Registration 1.0 incorporating errata set 1]
* xref:conf-client-mgmt-openam-task.adoc[To Configure Client Management By OpenAM]
* xref:conf-client-mgmt-pf-task.adoc[To Configure Client Management By PingFederate]
* xref:configure-client-management-openid-task.adoc[To Configure OpenID Connect Client Management]
