= Managing IP Allowlists in Access Management

Create IP allowlists in Access Management to restrict access to your Anypoint Platform organization to trusted networks. Enforce IP restrictions for Anypoint Platform logins by adding CIDR blocks to reduce credential abuse and meet compliance needs.

[NOTE]
--
* This feature is available only for US and EU commercial clouds.
* IP allowlisting applies only to users who sign in with Anypoint Platform credentials. It doesn't apply to users who authenticate through an external identity provider (IdP) using SSO.
--

== Before You Begin

* Have the root Organization Administrator permission for your organization.

[enable-disable-ip-allowlisting]
== Enable or Disable IP Allowlisting

Enable or disable IP allowlisting for your organization’s logins in Access Management. When this feature is enabled, only logins from IP addresses in allowed CIDR blocks succeed. Login attempts outside the IP allowlist are blocked and logged.

. Log in to Anypoint Platform using an account that has the root Organization Administrator permission.
. Select *Access Management* from the image:gear.svg["gear icon",20] menu.
. In the Access Management navigation menu, select *Security Settings*.
. In *IP Allowlist*, enter the IP address CIDR blocks to allow to log in. For example:
* IP Address CIDR: `192.0.2.0/24`
* Description: `NE office network`
+
[NOTE]
Only IPv4 addresses are supported. All defined CIDR blocks apply to all users in your organization unless they're exempted. 
. (Optional) Click *Add* or *Remove* to add and remove CIDR blocks. 
. Switch the *Enforce IP restrictions for login* switch on or off to activate or deactivate defined IP restrictions for all users within your organization.
+
If there aren't any CIDR blocks configured, this option is disabled.
. Click *Save*.

[ip-allowlist-exemptions]
== Manage IP Allowlist Exemptions

You can exempt specific users from the organization-wide IP allowlist restrictions.

[NOTE]
Root organization administrators are subject to IP enforcement unless explicitly exempted, and they're allowed to self-exempt.

. Log in to Anypoint Platform using an account that has the root Organization Administrator permission.
. Select *Access Management* from the image:gear.svg["gear icon",20] menu.
. In the Access Management navigation menu, select *Users*.
. Select the user to exempt and then select *Settings*. 
. Select *Exempt user from IP restrictions*, and then click *Save* to apply the exemption.

[control-plane-ip-addresses]
== Access Management Egress IP Addresses

Access Management uses these IP addresses for outbound connections. For example, when Access Management calls a Client Registration URL configured for OpenID Connect (OIDC) dynamic client registration, the request comes from one of these IP addresses. If you restrict inbound access to that endpoint, add these IP addresses to your allowlist.

* `52.6.166.106`
* `52.7.186.107`
* `34.236.135.39`
* `50.17.243.127`
* `52.0.137.105`
* `174.129.64.184`

[audit-logging]
== Audit Logging

These actions are logged in the audit log:

* Create, update, and delete actions performed by an Organization Administrator on the allowlist
* Signin failures due to IP restrictions

== See Also

* xref:managing-security-settings.adoc[]