= About Client Management
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

This topic provides an overview of client management on Anypoint Platform. As an API owner, you can apply an OAuth 2.0 policy to authenticate client applications that try to access your API. You need an OAuth provider to use an OAuth 2.0 policy.

Using the client management, you can configure several identity providers, or IdPs, to manage client credentials.
Any IdPs you configure are available in the master organization.
You can make them available to business group administrators to xref:environments.adoc#add-an-idp-to-an-existing-environment[associate the IdPs with different environments] depending on your organization's policies. When you delete an IdP from your master organization, the IdP is no longer available in environments that used it, and the APIs associated with it no longer use a client provider. As such, this breaks working contracts between APIs and client applications. 

You can configure the following OAuth providers:

* OpenAM version: 14
* PingFederate versions: 6 - 8
* Dynamic Client Registration-compliant identity providers
+
This provider needs to conform to the OpenID Connect Client Registration 1.0 incorporating errata set 1.

To configure client management on Anypoint Platform for these providers, you must have an IdP account.

== See Also

* https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Client Registration 1.0 incorporating errata set 1]
* xref:conf-client-mgmt-openam-task.adoc[To Configure Client Management By OpenAM]
* xref:conf-client-mgmt-pf-task.adoc[To Configure Client Management By PingFederate]
* xref:configure-client-management-openid-task.adoc[To Configure OpenID Connect Client Management]
