= Configure SAML for SSO
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Configure SAML to provide external authentication of users and Single Sign-on (SSO) capability so users don't need to provide additional credentials when they access Anypoint Platform.

Configuring SAML for SSO involves:

* Beginning with a configured SAML identity provider (IdP)
* Navigating to and completing the *External Identity - Identity Management SAML 2.0* form in Anypoint Platform, and optionally configuring some advanced settings
* Saving and testing your new configuration

== Prerequisites

* Your Anypoint Platform organization must be set up as your audience.
* The assertion consumer service must be set to send a `POST` request to `+https://anypoint.mulesoft.com/accounts/login/receive-id+`.

[NOTE]
====
* If you are using the Anypoint Platform EU Control Plane, the endpoint is `+https://eu1.anypoint.mulesoft.com/accounts/login/receive-id+`. +
* If you are using the Anypoint Platform Gov Cloud, the endpoint is  `+https://gov.anypoint.mulesoft.com/accounts/login/receive-id+`
====

[[configure-saml]]
== Configure SAML in Identity Management

. In Anypoint Platform, sign in as a user with the Organization Administrator permission.
. In *Management Center*, click *Access Management*.
. In the navigation menu on the left, click *Identity Providers*.
. Select *Identity Providers* > *SAML 2.0*.
. In the *Configurations* tab, complete the required fields of the *Identity Management SAML 2.0* form:
+
* *Sign On URL*
+
Redirect URL provided by the IdP for signin, for example: `+https://example.com/sso/saml+`.
+
* *Sign Off URL*
+
URL to redirect signout requests, so users both sign out of the Anypoint Platform and have their SAML user's status set to signed out.
+
* *Issuer*
+
ID of the identity provider instance that sends SAML assertions.
+
* *Public Key*
+
Public key provided by the identity provider, which is used to sign the SAML assertion.
+
* *Audience*
+
An arbitrary string value that identifies your Anypoint Platform organization. The typical value for this string is `<organizationDomain>.anypoint.mulesoft.com`.
+
* *Single Sign-On Initiation*
+
Specify whether SSO can be initiated by the Anypoint Platform, your identity provider (for example, Okta), or both. 

** The *Service Provider Only* option allows only the Anypoint Platform to initiate SSO. 
** The *Identity Provider Only* option allows only your external identity provider to initiate SSO. 
** The *Both* option allows either Anypoint Platform or your external identity provider to initiate SSO. 
+
The default value for this setting for newly configured identity provider configurations is *Both*.
+
. Optionally, expand *Advanced settings*, and provide the following values:
+
* *Username Attribute*
+
Field name in the SAML `AttributeStatements` that maps to username. If no value is configured, the `NameID` attribute of the SAML `Subject` is used (Note: this is outside the SAML `AttributeStatements`).
+
* *First Name Attribute*
+
Field name in the SAML `AttributeStatements` that maps to `First Name`.
+
* *Last Name Attribute*
+
Field name in the SAML `AttributeStatements` that maps to `Last Name`.
+
* *Email Attribute*
+
Field name in the SAML `AttributeStatements` that maps to `Email`.
+
* *Group Attribute*
+
Field name in the SAML `AttributeStatements` that maps to `Group`.
+
* *Require encrypted SAML assertions*
+
If enabled, the SAML assertions sent from the IdP must be encrypted and follow the guidelines mentioned in the xref:sso-prerequisites-about.adoc[Prerequisites].
+
. Click *Create*.
+
. Sign out of Anypoint Platform, navigate to the sign-on URL you entered in the *Identity Management SAML 2.0* form, then sign in through your identity provider to test the configuration.

== Rotate a SAML Key

As a security best practice, many organizations rotate the key used to encrypt SAML 2.0 assertions. With the Key Rotation feature, Anypoint Platform can generate a new key, or you can upload a public and private key pair (up to 3).

After you've added a new key to Anypoint Platform, you must ensure the key also exists in your IdP. All keys present in Anypoint Platform are used to decrypt SAML 2.0 assertions sent by your IdP. However, only the primary key is used by Anypoint Platform to sign SAML 2.0 AuthnRequests and SLO requests; the primary key must be configured in your IdP to validate the signatures.

If you are migrating from the default Anypoint Platform SSO certificate to a new certificate, you must update the Assertion Consumer Service (ACS) URL in your IdP. Only the new ACS URL supports the keys generated by the key rotation feature. If your ACS URL already follows the pattern of `.../accounts/login/:org-domain/providers/:providerId/receive-id`, you do not need to change the ACS URL.

=== Generate a Key

Anypoint Platform can create a key for you to use with your IdP.

. In Anypoint Platform, sign in as a user with the Organization Administrator permission.
. In *Management Center*, click *Access Management*.
. In the navigation menu on the left, click *Identity Providers*.
. Next to a SAML 2.0 IdP, click *Edit*.
. Click the *Anypoint Keys* tab.
. Click *+ New key*, and select *Generate*. +
A newly generated key appears in the list of keys.

=== Upload a Key

You can upload an existing public and private key pair.

. In Anypoint Platform, sign in as a user with the Organization Administrator permission.
. In *Management Center*, click *Access Management*.
. In the navigation menu on the left, click *Identity Providers*.
. Next to a SAML 2.0 IdP, click *Edit*.
. Click the *Anypoint Keys* tab.
. Click *+ New key*, and select *Upload*.
. In the *Private key* field, paste your private key.
. In the *Public key* field, paste your certificate.
. Click *Upload*. +
The key you uploaded appears in the list of keys.

=== Change the Primary Key

Because you can store up to 3 keys, you must designate a _primary key_ to be used for signing requests from Anypoint Platform.
Before reassigning the primary key, ensure your IdP can access the key that you intend to use.

. In Anypoint Platform, sign in as a user with the Organization Administrator permission.
. In *Management Center*, click *Access Management*.
. In the navigation menu on the left, click *Identity Providers*.
. Next to a SAML 2.0 IdP, click *Edit*.
. Click the *Anypoint Keys* tab.
. Next to the key that you want to make primary, click *...* and select *Use as primary key...*.
. Click *Apply*.

=== Revoke a Key

As a best practice, revoke a key that you have already used as the primary key.
Before you revoke a key, ensure your IdP is not using the key.
Note that when you revoke a public key, Anypoint Platform also revokes the corresponding private key. For security purposes, you cannot retrieve a key that has been revoked.

. In Anypoint Platform, sign in as a user with the Organization Administrator permission.
. In *Management Center*, click *Access Management*.
. In the navigation menu on the left, click *Identity Providers*.
. Next to a SAML 2.0 IdP, click *Edit*.
. Click the *Anypoint Keys* tab.
. Next to the key that you want to revoke, click *...* and select *Revoke*.
. Click *Revoke*.

== Import SAML Metadata

When creating a new SAML 2.0 configuration, you can upload an XML file containing your identity provider's SAML 2.0 metadata to Anypoint Platform using the *Import IdP Metadata* link. Once uploaded, the XML file's values automatically populate the *Identity Management SAML 2.0* form.

When you upload an XML file to import your metadata:

* The file must be smaller than 16 KB.
* If you upload an XML file that contains more than one entry, Anypoint Platform uses the first identity provider configuration.
* Anypoint Platform does not check the validity of the values in the XML that you upload. +
Verify that your identity configuration is correct before creating the identity provider configuration.

== Export SAML Metadata

If your identity provider supports uploading service-provider metadata, you can click the *Anypoint service provider metadata* link to download your SAML configuration settings in an XML file. You can then upload this file to your identity provider to configure Anypoint Platform. Note that you must have a SAML 2.0 identity configuration to export this data.


== SSO Redirect Process Using Cookies

Anypoint Platform uses cookies to ensure that SSO users are redirected to the same location from which they initiated their login.

. When a user logs in to Anypoint Platform, a cookie is created for the login session: `mulesoft.sess=xxxxx`. +
The cookie contains the location, such as a public portal, from which the user initiated the login.
. The cookie is passed to the user's browser.
. The user is directed to their SSO provider for authentication.
. After the user is authenticated using SSO, the provider directs the user back to Anypoint Platform with the authorization decision SAML response.
. The session cookie, `mulesoft.sess=xxxxx`, is passed from the browser, which redirects the user back to the location from which they initiated the login process.
. After the user successfully logs in to Anypoint Platform, the `mulesoft.sess` cookie returns to its default value, based on the OWASP standard.

Users can also be redirected based on their permissions. This occurs when:

* The browser does not pass a cookie.
* The cookie has expired.
* The cookie is set to the default value.

In these cases, a user with the Organization Administrator permission is redirected to the Anypoint Platform landing page. 
Users who do not have the Organization Administrator permission are directed to Anypoint Exchange.

== See Also

* xref:single-log-out-task.adoc[Configure Single Logout]
