= Managing Connected Salesforce Orgs

As an Anypoint Platform organization administrator, you can:

* <<enable-disable-connection,Enable or disable the connection>> to a Salesforce org.
* <<removing-connections,Remove the connection>> to a Salesforce org.
* <<repairing-org-connection,Repair the connection>> to a Salesforce org.
* <<edit-org-name,Edit the Salesforce org name>>.

[enable-disable-connection]
== Enable or Disable a Connection in Anypoint Platform

Enable the connection with a Salesforce org from your Anypoint Platform organization to the trusted Salesforce org. 

[NOTE]
Tenant relationships that automatically provisioned with your Anypoint Platform organization are disabled until you enable them. 

When you disable the connection, the Salesforce org still appears in the list of available organizations with a status of `Disabled`. When the connection is disabled, you can't publish assets from your Anypoint Platform organization to the Salesforce org or use any of the other features associated with the connected Salesforce org until the connection is reenabled. Disabling a connection does not remove the connection to the Salesforce org. 

include::partial$include-nav-steps-org-admin.adoc[]

. Click *Salesforce*.
+
If your organization has at least one established tenant relationship with a Salesforce org, a list of Salesforce orgs appears, showing the name, org ID, and status of the relationship connection.
. Click *Enable* or *Disable* for the Salesforce org you want to enable or disable the connection for.

[[removing-connections]]
== Remove the Connection Between Anypoint Platform and Salesforce Organizations

You can remove the connection between Anypoint Platform organizations and Salesforce organizations. When the connection is removed, the Salesforce org no longer appears in the list of connected organizations. The connection still exists in the Salesforce org until it's removed by the Salesforce admin.

To reestablish the connection between Anypoint Platform and removed Salesforce organizations, administrators with the appropriate permissions in both Anypoint Platform and Salesforce organizations must recreate the connection.

[removing-connection-anypoint-platform]
=== Remove a Connected Salesforce Org in Anypoint Platform

An Anypoint Platform organization administrator can remove the connection between their Anypoint Platform organization and connected Salesforce orgs.

When you remove a connection to a Salesforce org, any capabilities that are associated with the Salesforce org, such as API Catalog, are removed. 

To remove the connection to a Salesforce org:

include::partial$include-nav-steps-org-admin.adoc[]

. Click *Salesforce*.
. Click the *Actions* menu (*...*) in the Salesforce org to remove the connection from and select *Remove Salesforce Org*. 
. In the *Remove Salesforce Org* dialog, click *Remove Org*.

[removing-connection-salesforce]
=== Remove a Connected Anypoint Platform Organization in Salesforce

A Salesforce org admin can remove the connection between an Anypoint Platform organization and Salesforce org using the Salesforce user interface. 

To remove the connection to an Anypoint Platform organization:

include::partial$include-salesforce-mulesoft-setup-nav.adoc[]

. In the *Your connected Anypoint Platform Organization* section, click *View Connection Info*.
. In the *Go To Anypoint* drop-down list, select *Remove connection.*
. In the *Remove connection to Anypoint Platform* dialog box, click *OK*.

Alternatively, if you want to temporarily prevent Anypoint Platform users from publishing assets to Salesforce from the Anypoint Platform side, you can instead <<enable-disable-connection,disable>> the connection temporarily.

For more information about managing this relationship from the Salesforce user interface, see the https://help.salesforce.com/s/articleView?id=sf.external_services_manage_your_mulesoft_anypoint_platform_connection.htm&type=5[Salesforce documentation]. 

[[repairing-org-connection]]
== Repair the Connection to a Salesforce Org

If the Salesforce *My Domain* is changed in the connected Salesforce org, you can rediscover the Salesforce org and repair the connection. 

include::partial$include-nav-steps-org-admin.adoc[]

. Click *Salesforce*.
. Click the *Actions* menu (*...*) in the Salesforce org to repair the connection for and select *Repair Org Info*.
. Click *Repair* to rediscover the Salesforce org. 

[[edit-org-name]]
== Edit the Salesforce Organization name

You can edit the Salesforce org display name in your Anypoint Platform organization. This doesn't change the name of the Salesforce org within Salesforce. 

To edit a Salesforce org name:

include::partial$include-nav-steps-org-admin.adoc[]

. Click *Salesforce*.
. Click the *Actions* menu (*...*) in the Salesforce org to edit the name for and select *Edit Org Name*. 
. Enter the name for the Salesforce org and click *Save*.
+
The Salesforce org name appears in Anypoint Platform anywhere the org is referenced.

== Copy Your Anypoint Platform Organization ID

include::partial$include-nav-steps-org-admin.adoc[]

. Click *Salesforce*.
. Click the *Actions* menu (*...*) and select *Get Anypoint Platform Organization ID*.
. Click *Copy*. 


== See Also

* xref:trusted-salesforce-org.adoc[]
* xref:manage-capabilities.adoc[]