= About Client Management
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform acts as a client provider by default, but you can also configure other client providers to authorize client applications. As an API owner, you can apply an OAuth 2.0 policy to authorize client applications that try to access your API. You need an OAuth 2.0 provider to use an OAuth 2.0 policy.

You can configure more than one client provider and xref:environments.adoc#add-an-idp-to-an-existing-environment[associate the client providers with different environments].
Configuring multiple client providers enables you to use client providers for different purposes, such as giving production and developer environments different providers.
If you configure multiple client providers after you have already created environments, you can associate the new client providers with the environment. You should review the existing client configuration before reassigning client providers to avoid any downtime with existing assets. 
When you delete a client provider from your master organization, the client provider is no longer available in environments that used it. Also, assets that used the client provider can no longer authorize users who want to access them.

You can configure the following OAuth providers:

* xref:conf-client-mgmt-openam-task.adoc[OpenAM version: 14]
* xref:conf-client-mgmt-pf-task.adoc[PingFederate versions: 6 through 8]
* xref:configure-client-management-openid-task.adoc[Dynamic Client Registration-compliant identity providers]
+
Dynamic Client Registration-compliant identity providers must conform to the https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Client Registration 1.0 incorporating errata set 1].

To configure client management on Anypoint Platform for these providers, you must have an IdP account.



== Delete a Client Provider

[WARNING]
Before you delete a client provider, ensure that you do not have assets or environments that depend on the client provider or you will lose functionality. For example, any APIs that depend on the client provider can no longer authenticate user access.

. Log in to Anypoint Platform using an account that has the organization administrator role.
. In Anypoint Platform, click *Access Management*.
. In the menu on the left, click *Client Providers*.
. Click the name of the client provider you want to delete.
. In the client provider's page, click *Delete*.
. Enter the name of the client identity provider name.
. Click *Delete*.

== See Also

* https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Client Registration 1.0 incorporating errata set 1]
* xref:conf-client-mgmt-openam-task.adoc[Configure Client Management by OpenAM]
* xref:conf-client-mgmt-pf-task.adoc[Configure Client Management by PingFederate]
* xref:configure-client-management-openid-task.adoc[Configure OpenID Connect Client Management]
