= About Client Management
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Platform acts as a client provider by default, but you can also configure up to 25 external client providers to authorize client applications. As an API owner, you can apply an OAuth 2.0 policy to authorize client applications that try to access your API. You need an OAuth 2.0 provider to use an OAuth 2.0 policy.

You can configure more than one client provider and xref:environments.adoc#add-an-idp-to-an-existing-environment[associate the client providers with different environments].
If you configure multiple client providers after you have already created environments, you can associate the new client providers with the environment. You should review the existing client configuration before reassigning client providers to avoid any downtime with existing assets or APIs.
When you delete a client provider from your root organization, the client provider is no longer available in environments that used it. Also, assets or APIs that used the client provider can no longer authorize users who want to access them.

You can configure the following OAuth providers:

* xref:conf-client-mgmt-openam-task.adoc[OpenAM version: 14]
* xref:conf-client-mgmt-pf-task.adoc[PingFederate versions: 6 through 8]
* xref:configure-client-management-openid-task.adoc[Dynamic Client Registration-compliant client providers]
 ** xref:configure-client-management-azure.adoc[Azure Active Directory Client Management]

+
Dynamic Client Registration-compliant identity providers must conform to the https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Client Registration 1.0 incorporating errata set 1].

To configure client management on Anypoint Platform for supported providers, you must have an identity provider (IdP) account with the provider you want to use.

== Delete a Client Provider

[WARNING]
Before you delete a client provider, ensure that you do not have APIs, assets, or environments that depend on the client provider or you will lose functionality. For example, any APIs that depend on the client provider can no longer authenticate user access.

include::partial$include-nav-steps-org-admin-bg.adoc[]

include::partial$include-nav-client-providers.adoc[]

. Click the name of the client provider you want to delete.
. In the client provider's page, click *Delete*.
. Enter the name of the client identity provider name.
. Click *Delete*.

== See Also

* https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Client Registration 1.0 incorporating errata set 1]
* xref:conf-client-mgmt-openam-task.adoc[Configure Client Management by OpenAM]
* xref:conf-client-mgmt-pf-task.adoc[Configure Client Management by PingFederate]
* xref:configure-client-management-openid-task.adoc[Configure OpenID Connect Client Management]
