= Manage Capabilities in Access Management

When you connect your Anypoint Platform organization with a Salesforce organization, you see the status of the capabilities that are associated with the Salesforce organization. 

Capabilities include features that are visible and can be managed in both the Anypoint Platform organization and the connected Salesforce organization. Enablement of capabilities is done either in Anypoint Platform or in the Salesforce organization, depending on the capability. 

== Enabling Invocable Actions for Your Salesforce Organization

The Salesforce organization administrator enables the invocable actions capability within the Salesforce organization in the MuleSoft *Setup* page. 

include::partial$include-salesforce-mulesoft-setup-nav.adoc[]

. In the *Your connected Anypoint Platform Organization* section, click *View Connection Info*.
. In the *Connection to MuleSoft Anypoint Platform* window, turn on *Enable Invocable Actions from Anypoint Automations.*
+
After the Salesforce organization administrator enables this feature, *Enabled in Salesforce* is displayed. 

== Making Anypoint Platform APIs Available in a Salesforce Organization

Enable a connected Salesforce organization to access and import Anypoint Platform APIs into the Salesforce API Catalog and expose them as invocable actions. This capability is managed in Anypoint Platform access management and must be enabled by an Anypoint Platform organization administrator.

To enable this feature:

include::partial$include-nav-steps-org-admin.adoc[]

. Click *Salesforce*.
. In the *Capabilities Managed in Anypoint Platform* section, click *Settings* next to *Make MuleSoft Anypoint Platform APIs Available in Salesforce*.
. In *Settings for Anypoint APIs in Salesforce*, read the information, and then click *Continue*.
. In the next window, select which APIs to make available to the connected Salesforce organization, and then click *Save settings*.
+
This feature is now enabled. 

[NOTE]
The Salesforce administrator must select individual API operations to expose to selected Salesforce developers. After an API operation is assigned to a developer, an access request is sent to the owner of the API. 

== See Also

ADD LINK TO API CATALOG DOCUMENTATION


