= Client Management in Anypoint Platform

Configure up to 25 external client providers in Anypoint Platform to authorize API client applications. Apply OAuth 2.0 policies to protect your APIs, using your chosen OAuth 2.0 provider. This enables you to centralize and scale client authorization across environments.

[[supported-oauth-2-0-providers]]
== Supported OAuth 2.0 Providers

To configure client management on Anypoint Platform for supported providers, you must have an identity provider (IdP) account with the provider to use.

You can configure these OAuth 2.0 providers:

* xref:conf-client-mgmt-openam-task.adoc[OpenAM version: 14]
* xref:conf-client-mgmt-pf-task.adoc[PingFederate versions: 6 through 8]
* xref:configure-client-management-openid-task.adoc[Dynamic Client Registration-compliant client providers]
 ** xref:configure-client-management-entra-id.adoc[Microsoft Entra ID Client Management]
 +
Dynamic Client Registration-compliant identity providers must conform to the https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Client Registration 1.0 incorporating errata set 1].

[[multiple-client-providers]]
== Multiple Client Providers

You can configure more than one client provider and xref:environments.adoc#add-an-idp-to-an-existing-environment[associate the client providers with different environments].

If you configure multiple client providers after you create environments, you can associate the new client providers with the environment. Review the existing client configuration before reassigning client providers to avoid any downtime with existing assets or APIs.

[[delete-client-provider]]
== Delete a Client Provider

When you delete a client provider from your root organization, the client provider is no longer available in environments that used it. Also, assets or APIs that used the client provider can no longer authorize users who want to access them.

[WARNING]
Before you delete a client provider, make sure that you don't have APIs, assets, or environments that depend on the client provider or you will lose functionality. For example, any APIs that depend on the client provider can no longer authenticate user access.

include::partial$include-nav-steps-org-admin-bg.adoc[]

include::partial$include-nav-client-providers.adoc[]

. Click the name of the client provider you want to delete.
. In the client provider's page, click *Delete*.
. Enter the name of the client identity provider name.
. Click *Delete*.

== See Also

* https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Client Registration 1.0 incorporating errata set 1]
* xref:conf-client-mgmt-openam-task.adoc[]
* xref:conf-client-mgmt-pf-task.adoc[]
* xref:configure-client-management-openid-task.adoc[]
* xref:api-manager::migrate-client-apps.adoc#migrate_with_external[Migrate Client Applications for APIs with External Client Providers in API Manager]
