= Configure SAML for SSO
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Configure SAML to provide external authentication of users and Single Sign-on (SSO) capability so users don't need to provide additional credentials when they access Anypoint Platform.

Configuring SAML for SSO involves:

* Beginning with a configured SAML identity provider (IdP)
* Navigating to and completing the *External Identity - Identity Management SAML 2.0* form in Anypoint Platform, and optionally configuring some advanced settings
* Saving and testing your new configuration

== Prerequisites

* Your Anypoint Platform organization must be set up as your audience.
* The assertion consumer service must be set to send a `POST` request to `+https://anypoint.mulesoft.com/accounts/login/receive-id+`.

[NOTE]
====
* If you are using the Anypoint Platform EU Control Plane, the endpoint is `+https://eu1.anypoint.mulesoft.com/accounts/login/receive-id+`. +
* If you are using the Anypoint Platform Gov Cloud, the endpoint is  `+https://gov.anypoint.mulesoft.com/accounts/login/receive-id+`
====

[[configure-saml]]
== Configure SAML in Identity Management

. In Anypoint Platform, sign in as a user with the Organization Administrator permission.
. In *Management Center*, click *Access Management*.
. In the navigation menu on the left, click *Identity Providers*.
. Select *Identity Providers* > *SAML 2.0*.
. Complete the required fields of the *Identity Management SAML 2.0* form:
+
* *Sign On URL*
+
Redirect URL provided by the IdP for signin, for example: `+https://example.com/sso/saml+`.
+
* *Sign Off URL*
+
URL to redirect signout requests, so users both sign out of the Anypoint Platform and have their SAML user's status set to signed out.
+
* *Issuer*
+
ID of the identity provider instance that sends SAML assertions.
+
* *Public Key*
+
Public key provided by the identity provider, which is used to sign the SAML assertion.
+
* *Audience*
+
An arbitrary string value that identifies your Anypoint Platform organization. The typical value for this string is `<organizationDomain>.anypoint.mulesoft.com`.
+
* *Single Sign-On Initiation*
+
Specify whether SSO can be initiated by the Anypoint Platform, your identity provider (for example, Okta), or both. 

** The *Service Provider Only* option allows only the Anypoint Platform to initiate SSO. 
** The *Identity Provider Only* option allows only your external identity provider to initiate SSO. 
** The *Both* option allows either Anypoint Platform or your external identity provider to initiate SSO. 
+
The default value for this setting for newly configured identity provider configurations is *Both*.
+
. Optionally, expand *Advanced settings*, and provide the following values:
+
* *Username Attribute*
+
Field name in the SAML `AttributeStatements` that maps to username. If no value is configured, the `NameID` attribute of the SAML `Subject` is used (Note: this is outside the SAML `AttributeStatements`).
+
* *First Name Attribute*
+
Field name in the SAML `AttributeStatements` that maps to `First Name`.
+
* *Last Name Attribute*
+
Field name in the SAML `AttributeStatements` that maps to `Last Name`.
+
* *Email Attribute*
+
Field name in the SAML `AttributeStatements` that maps to `Email`.
+
* *Group Attribute*
+
Field name in the SAML `AttributeStatements` that maps to `Group`.
+
* *Require encrypted SAML assertions*
+
If enabled, the SAML assertions sent from the IdP must be encrypted and follow the guidelines mentioned in the xref:sso-prerequisites-about.adoc[Prerequisites].
+
. Click *Create*.
+
. Sign out of Anypoint Platform, navigate to the sign-on URL you entered in the *Identity Management SAML 2.0* form, then sign in through your identity provider to test the configuration.

== Import SAML Metadata

When creating a new SAML 2.0 configuration, you can upload an XML file containing your identity provider's SAML 2.0 metadata to Anypoint Platform using the *Import IdP Metadata* link. Once uploaded, the XML file's values automatically populate the *Identity Management SAML 2.0* form.

When you upload an XML file to import your metadata:

* The file must be smaller than 16 KB.
* If you upload an XML file that contains more than one entry, Anypoint Platform uses the first identity provider configuration.
* Anypoint Platform does not check the validity of the values in the XML that you upload. +
Verify that your identity configuration is correct before creating the identity provider configuration.

== Export SAML Metadata

If your identity provider supports uploading service-provider metadata, you can click the *Anypoint service provider metadata* link to download your SAML configuration settings in an XML file. You can then upload this file to your identity provider to configure Anypoint Platform. Note that you must have a SAML 2.0 identity configuration to export this data.


== SSO Redirect Process Using Cookies

Anypoint Platform uses cookies to ensure that SSO users are redirected to the same location from which they initiated their login.

. When a user logs in to Anypoint Platform, a cookie is created for the login session: `mulesoft.sess=xxxxx`. +
The cookie contains the location, such as a public portal, from which the user initiated the login.
. The cookie is passed to the user's browser.
. The user is directed to their SSO provider for authentication.
. After the user is authenticated using SSO, the provider directs the user back to Anypoint Platform with the authorization decision SAML response.
. The session cookie, `mulesoft.sess=xxxxx`, is passed from the browser, which redirects the user back to the location from which they initiated the login process.
. After the user successfully logs in to Anypoint Platform, the `mulesoft.sess` cookie returns to its default value, based on the OWASP standard.

Users can also be redirected based on their permissions. This occurs when:

* The browser does not pass a cookie.
* The cookie has expired.
* The cookie is set to the default value.

In these cases, a user with the Organization Administrator permission is redirected to the Anypoint Platform landing page. 
Users who do not have the Organization Administrator permission are directed to Anypoint Exchange.

== See Also

* xref:single-log-out-task.adoc[Configure Single Logout]
