= Enabling and Managing Multi-Factor Authentication in Anypoint Platform

Anypoint Platform multi-factor authentication (MFA) adds a second verification step when users sign in with their Anypoint Platform credentials or via single sign-on (SSO). MuleSoft requires MFA for all users. You can also register authenticator apps, security keys, or built-in device authentication. Organization administrators configure exempt service accounts and reset MFA for individual users when needed.

MFA is enabled by default for direct signins and can’t be turned off at the organization level. However, a few service account types don’t require MFA. An organization administrator can waive MFA for these accounts so that existing integrations can continue without interruption.

[NOTE]
====
For SSO users, set up MFA through the identity provider (IdP). Because MFA is managed by the IdP, multi-factor authentication is shown as `n/a` in user Settings for SSO users.
====

When a user signs in with their Anypoint Platform credentials, they must enter their password and then verify their identity with one of these verification methods:

* Third-party TOTP authenticator apps
* Built-in authenticator
* Security key
* Salesforce Authenticator

[[mfa-requirements-salesforce-mulesoft]]
== Multi-Factor Authentication Requirements for Salesforce and MuleSoft Products

* Effective February 1, 2022, MFA must be enabled for all of your Anypoint Platform users. To learn more about this contractual requirement, see the https://help.salesforce.com/s/articleView?id=Salesforce-Multi-Factor-Authentication-FAQ&language=en_US&type=1[Salesforce Multi-Factor Authentication FAQ].
* As of October 29, 2022, all non-SSO accounts that don't have MFA configured are prompted to register for an MFA verification method and use it to sign in to Anypoint Platform.

[[mfa-verification-methods]]
== Multi-Factor Authentication Verification Methods

You can configure at least one of these verification methods to comply with multi-factor authentication requirements:

Third-party TOTP authenticator app:: Registers an authenticator app to create verification codes that you provide when you sign in to Anypoint Platform.

Built-in authenticator:: Registers a physical authentication device, such as Touch ID or Windows Hello, to verify your identity when you sign in to Anypoint Platform.

Security key:: Registers a security key, such as Yubico YubiKey or Google Titan Security Key, to your account. Connect the security key to your computer to verify your identity when you sign in to Anypoint Platform.

Salesforce Authenticator:: Registers the Salesforce Authenticator mobile app to send you push notifications verifying your identity when you sign in to Anypoint Platform.

[[exempt-mfa-users]]
== Exclude Exempt Accounts from Multi-Factor Authentication

These types of service accounts are exempt from the requirement to use MFA:

* Test automation tools, such as Selenium, Cucumber, or Appium
* Robotic Process Automation (RPA) systems, such as Automation Anywhere

[IMPORTANT]
MuleSoft requires customers to use xref:connected-apps-org-admin.adoc[internal connected apps] instead of service accounts that make programmatic calls to Anypoint Platform. Connected apps provide more security and control than service accounts. If you’re having trouble switching to connected apps, reach out to MuleSoft for help. In the meantime, you can temporarily waive MFA for your existing service accounts until they’re transitioned to connected apps.

To prevent service disruptions, waive MFA for valid MFA-exempt accounts in your organization. After August 1, 2023, waiving MFA for user accounts isn't permitted.

include::partial$include-nav-steps-org-admin-bg.adoc[]

include::partial$include-nav-mfa.adoc[]

. Select your Anypoint Platform identity provider.
. In the *Exempt Accounts* section, add the accounts that are valid to exclude from MFA. +
Only accounts that don't use single sign-on (SSO) appear in this list.
. Click *Save*. +
The exempt accounts appear in the *Exempt Accounts* section.

You can later remove user accounts from the *Exempt Accounts* list by clicking *X* next to their account names.

[[manage-mfa-for-your-account]]
== Manage Multi-Factor Authentication for Your Account

You can modify the verification methods that you use to sign in. You must register at least one method to use MFA.

To modify verification methods in your account:

include::partial$include-nav-steps-to-profile.adoc[]

. Select *Configure multi-factor authentication (MFA)*. 
. To register an additional verification method:
.. Next to the verification method to configure, click *Add*.
.. Follow the instructions to configure your preferred verification method.
.. Click *Done*. +
. To modify the name of an existing verification method:
.. Select the pencil icon next to the verification method to rename.
.. Enter a new name for your verification method.
.. Select the checkmark.
.. Click *Done*. +
. To remove a verification method:
.. Next to the verification method to remove, select the bin icon.
.. Click *Yes*.
.. Click *Done*.  +
[NOTE]
If you removed all verification methods, you must configure at least one verification method before you save your changes.
. Click *Save*.

[[reset-mfa-for-individual-users]]
== Reset Multi-Factor Authentication for Individual Users

You can reset multi-factor authentication for individual users if a device is compromised or lost. If you're the only organization member with Organization Administrator permission and have lost access to your verification methods, contact customer support.

To reset multi-factor authentication for an individual user:

include::partial$include-nav-steps-org-admin-bg.adoc[]

include::partial$include-nav-users.adoc[]

. Select the user to reset multi-factor authentication for. 
. From the actions menu (*...*), select *Reset multi-factor authentication*.
. Click *Confirm reset MFA*. 
+
Next time the user signs in to Anypoint Platform, they're prompted to configure a new verification method.

== See Also

* xref:managing-security-settings.adoc[]
* xref:managing-your-account.adoc[]
