= Organizations

When you create an Anypoint Platform account, a root organization (business group) is created, and you are assigned as the owner of the organization. A root organization is a single instance of Anypoint Platform that includes all the entitlements, features, and capabilities you purchased. The owner of the root organization automatically inherits the Organization Administrator permission.

The organization name is the name you entered in the *Company* field in the initial Anypoint Platform signup form. You can change the name in the organization settings.

An organization is an account where multiple users can share resources, including applications and environments. The level of access users have to various resources depends on their assigned roles and permissions. For example, one user might have permission to manage API alerts, while another user has permission only to view API alerts.

When you sign in to Anypoint Platform, the organization icon and name are displayed on the top right of the page. The root organization can contain multiple business groups. You can think of business groups as sub-organizations, or children of the root organization. Click the organization icon to navigate between business groups.

== Organization Owner

The user who first signs up for an Anypoint Platform account is designated as the organization owner. This is not a permission that is assigned, rather it is an identifier for this single user (creator of the Anypoint Platform account). The Organization Administrator permission is assigned to the organization owner by default and can't be removed from the organization owner. 

When ownership of an organization is transferred to another user, the original organization owner retains the Organization Administrator permission unless you explicitly revoke it.

Every business group created within the organization hierarchy must have an owner with the Organization Administrator permission assigned. Any organization administrator can assign and change owners of business groups. There can't be multiple owners for a business group. 

[[org-admin]]
== Organization Administrator

An Anypoint Platform user who has the Organization Administrator permission can perform the following types of tasks:

* Invite users to an organization
* Assign users to teams or roles that define their permissions in Anypoint Platform
* Edit and remove users from an organization
* Assign or change owners of business groups
* Configure organization settings
* Create and manage teams
* View a client ID and client secret for the root organization, business groups, and environments
* Access analytics for the APIs in your organization
* Create business groups to delegate management of the resources and define the scopes of roles and permissions
* Configure additional properties at the business group level.

== See Also

* xref:managing-business-groups.adoc[]
* xref:business-groups.adoc[Business Groups]
* xref:roles.adoc[Roles]
* xref:teams.adoc[Teams]
* xref:managing-permissions.adoc[Managing Permissions]
* xref:environments.adoc[Environments]