= Permissions Available in Anypoint Platform
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The following permissions can be assigned to xref:teams.adoc[teams], granted to xref:users.adoc#grant-user-permissions[individual users], or combined to xref:roles.adoc#create-custom-roles[create custom roles (deprecated)]. 

When you configure permissions, note that some products require permissions from other products to use them properly. For example, Anypoint Monitoring requires users to have certain Runtime Manager permissions in addition to Anypoint Monitoring-related permissions. Depending on your organization, its licensing, and its entitlements, you might not see all of these permissions during configuration. 

== Access Management

Organization Administrator:: At the root organization level, grants a user most permissions available in Anypoint Platform, including but not limited to secrets management, network administration, and other view, modify, execute, and delete permissions. The Organization Administrator permission also grants access to the Organization Administration page, where the user can add and manage users and permissions, view and edit organization details, access API Manager > Client Applications, access the client ID and client secret for the organization, and customize the theme of the Developer Portal. This permission enables a user to edit all versions of all APIs, all registered applications, and all API Portals in Anypoint Platform. +
For security reasons, MuleSoft recommends distributing this permission to as few users as possible.

Audit Log Config Manager:: Enables a user to configure the retention period for audit logs over their organization. You must apply this permission at the root organization level. This permission appears only if you have *Try new features* or the Teams feature enabled in Access Management.

Audit Log Viewer:: Enables a user to view audit logs in Access Management.

== Anypoint Code Builder

// needs to drop the anypoint in the UI

Anypoint Code Builder Developer:: Enables a user to create and use Anypoint Code Builder WebIDE instances.

== Anypoint Monitoring

// this needs to drop the anypoint in the UI

Anypoint Monitoring Administrator:: Enables a user to view, create, modify, and delete content in Anypoint Monitoring.

Anypoint Monitoring Viewer:: Enables a user to view but not modify content in Anypoint Monitoring.

== API Catalog

API Catalog Contributor:: Enables a user to catalog assets and other resources using API Catalog.

== API Experience Hub

API Experience Hub Admin:: Enables a user to view, create, modify, and delete content in API Experience Hub.

API Experience Hub Community User:: Enables a user to view but not modify content in API Experience Hub.

== API Governance

Governance Administrator:: Enables a user to manage profiles and view reports.

== API Manager

Depending on your organization, you might see one of the following sets of permissions available for API Manager.

include::partial$include-permissions-api-manager-post-crowd.adoc[]

Or:

include::partial$include-permissions-api-manager-pre-crowd.adoc[]

////

== Composer

Unlisted for now but will need to be cleaned up

Composer User:: ?

Composer Admin:: ?
////

== Data Gateway

Data Gateway Administrator:: Enables a user to have full access to Data Gateway Designer.

Data Gateway Viewer:: Enables a user to have read only access to Data Gateway Designer.

== DataGraph

Contribute:: Enables a user to add source APIs to the unified schema, edit any source API schema added to the unified schema, request access to run queries, promote API schemas to an environment, view query traces in real time while running queries from the UI, and download a copy of the unified schema from the query editor.

Consume:: Enables a user to view and explore the unified schema, request access to run queries and make data requests from the UI, and download a copy of the unified schema from the query editor.

Operate:: Enables a user to view customer-facing logs and set a dedicated load balancer URL for Anypoint Datagraph.

DataGraph Admin:: Enables a user to contribute, consume, and operate the unified schema and view usage metrics.

DataGraph Project - Contributor:: Enables a user to add source APIs to the unified schema, edit any source API schema added to the unified schema, request access to run queries, promote API schemas to an environment, view query traces in real time while running queries from the UI, and download a copy of the unified schema from the query editor in a specific project.

DataGraph Project - Operator:: Enables a user to view customer-facing logs and set a dedicated load balancer URL for Anypoint Datagraph in a specific project.

DataGraph Project - Admin::  Enables a user to contribute, consume, and operate the unified schema and view usage metrics in a specific project.

== Design Center

Design Center Developer:: Enables a user to create and manage any project from the organization.

Design Center Creator:: Enables a user to create and administrate their own projects projects.

Design Center Viewer:: Enables a user to view all Design Center projects.

// where did the project-level permissions go?

== Exchange

Exchange Administrator:: Enables a user to view, create, share, deprecate, delete, and download assets within a business group. Also enables a user to edit asset portal content for an existing asset version.

Exchange Contributor:: Enables a user to view, create, and download assets within a business group. Also enables a user to edit asset portal content in an existing asset version.

Exchange Viewer:: Enables a user to view and download assets within a business group. Also enables a user to edit asset portal content in an existing asset version.

Exchange Creator:: Enables a user to create assets within a business group.

////
Where did thesse go?

Asset level permissions:

Asset Administrator
Asset Contributor
Asset Viewer
////

////

no but actually where did these go? 

== MQ

Clear destinations
Manage clients
Manage destinations
View clients
View destinations

== Partner Manager

Depending on your organization, you might see one of the following sets of permissions available for Anypoint Partner Manager.

Partner Manager Administrator
View Host, Partners and Message Flows
Manage Partners and Message Flows
Manage Activity
Manage Host
View Activity

Or:

Manage Partners
Manage Transactions
Partners Administrator
View Partners
View Transactions

////

== Runtime Manager

CloudHub Network Administrator:: Enables a user to manage CloudHub network resources.

CloudHub Network Viewer:: Enables a user to view CloudHub network resources.

Delete Applications:: Enables a user to delete applications in a specific environment.

Download Applications:: Enables a user to download application files in a specific environment.

Manage Alerts:: Enables a user to create, update, and delete application alerts in a specific environment.

Manage Application Data:: Enables a user to create and delete application data in a specific environment.

Manage Queues:: Enables a user to clear application queues in a specific environment.

Read Runtime Fabric:: Enables a user to query Runtime Fabrics in the organization.

Manage Runtime Fabrics:: Enables a user to read, create, update and delete Runtime Fabric resources.

Manage Runtime Fabric:: Enables a user to read, create, update and delete Runtime Fabric resources. 
// what is the deal here?

Manage Schedules:: Enables a user to run and update application schedules in a specific environment.

Manage Settings:: Enables a user to update application settings in a specific environment.

Manage Tenants:: Enables a user to create, update, and delete application tenants in a specific environment.

Read Alerts:: Enables a user to view alerts in a specific environment.

Read Applications:: Enables a user to view applications in a specific environment.

Manage Servers:: Enables a user to create, update, and delete server and flex gateways resources.

Read Servers:: Enables a user to view server and flex gateways resources.

Manage Application Flows:: Enables a user to update flows.

Create Applications:: Enables a user to create applications in a specific environment.


== Secrets Manager

Grant access to secrets:: Enables a user to browse, read metadata and grant access to secrets in a specific environment.

Manage secret groups:: Enables a user to create, modify, delete, read, and clone secret groups in a specific environment, as well to check if the user can initiate a new clone or restore operation.

Read secrets metadata:: Enables a user to browse and read metadata of secrets in a specific environment.

Write secrets:: Enables a user to upload, create, modify secrets in a specific environment.

////
== Tokenization

Where did this go?...not in QAX

Manage Tokenization Services:: ?

Manage Tokenization Formats:: ?
////

== Usage

Usage Viewer:: Enables a user to view usage reports.

== Visualizer

Visualizer Editor:: Enables a user to view, create, modify, and delete content in Anypoint Visualizer.
