= Permissions Available in Anypoint Platform
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The following permissions can be assigned to xref:teams.adoc[teams], granted to xref:users.adoc#grant-user-permissions[individual users], or combined to xref:roles.adoc#create-custom-roles[create custom roles].

== Access Management

Organization Administrator:: At the root organization level, grants a user most permissions available in Anypoint Platform, including but not limited to secrets management, network administration, and other view, modify, execute, and delete permissions. The Organization Administrator permission also grants access to the Organization Administration page, where the user can add and manage users and permissions, view and edit organization details, access API Manager > Client Applications, access the client ID and client secret for the organization, and customize the theme of the Developer Portal. This permission enables a user to edit all versions of all APIs, all registered applications, and all API Portals in Anypoint Platform. +
For security reasons, MuleSoft recommends distributing this permission to as few users as possible.

Audit Log Config Manager:: Enables a user to configure the retention period for audit logs over their organization. You must apply this permission at the root organization level. This permission appears only if you have *Try new features* or the Teams feature enabled in Access Management.

Audit Log Viewer:: Enables a user to view audit logs in Access Management.

== Anypoint Code Builder

// needs to drop the anypoint in the UI

Anypoint Code Builder Developer:: Enables a user to create and use Anypoint Code Builder WebIDE instances.

== Anypoint Monitoring

// this needs to drop the anypoint in the UI

Anypoint Monitoring Administrator:: Enables a user to view, create, modify, and delete content in Anypoint Monitoring.

Anypoint Monitoring Viewer:: Enables a user to view but not modify content in Anypoint Monitoring.

== API Catalog

API Catalog Contributor:: Enables a user to catalog assets and other resources using API Catalog.

== API Experience Hub

API Experience Hub Admin:: Enables a user to view, create, modify, and delete content in API Experience Hub.

API Experience Hub Community User::  Enables a user to view but not modify content in API Experience Hub.

== API Governance

Governance Administrator:: Enables a user to manage profiles and view reports.

== API Manager

Depending on your organization, you might see one of the following sets of permissions available for API Manager.

API Manager Environment Administrator
API Group Administrator
Deploy API Proxies
Manage API Alerts
Manage APIs Configuration
Manage Contracts
Manage Policies
View API Alerts
View APIs Configuration
View Contracts
View Policies

Or:

API Creator
API Versions Owner
Portals Viewer

////
== Composer

Unlisted for now, but they need to beef these up before they can be posted.

Composer User:: ?

Composer Admin:: ?
////

== Data Gateway

Data Gateway Administrator:: Enables a user to have full access to Data Gateway Designer.

Data Gateway Viewer:: Enables a user to have read only access to Data Gateway Designer.

== DataGraph

Contribute:: 

Consume:: 

Operate:: 

DataGraph Admin:: Enables a user to contribute, consume, and operate the unified schema and view usage metrics.

== Design Center

Organization level permissions:

Design Center Developer
Design Center Creator
Design Center Viewer

Project level permissions:

Project Administrator
Project Editor
Project Viewer

== Exchange

Organization level permissions:

Exchange Administrator
Exchange Contributor
Exchange Viewer

Asset level permissions:

Asset Administrator
Asset Contributor
Asset Viewer

== MQ

Clear destinations
Manage clients
Manage destinations
View clients
View destinations

== Partner Manager

Depending on your organization, you might see one of the following sets of permissions available for Anypoint Partner Manager.

Partner Manager Administrator
View Host, Partners and Message Flows
Manage Partners and Message Flows
Manage Activity
Manage Host
View Activity

Or:

Manage Partners
Manage Transactions
Partners Administrator
View Partners
View Transactions

== Runtime Manager

Cloudhub Network Administrator
Cloudhub Network Viewer
Delete Applications
Download Applications
Manage Alerts
Manage Application Data
Manage Queues
Manage Runtime Fabrics
Manage Runtime Fabric
Manage Schedules
Manage Settings
Manage Tenants
Read Alerts
Read Applications
Read Runtime Fabric
Manage Servers
Read Servers
Manage Application Flows
Create Applications

== Secrets Manager

Grant access to secrets:: Enables a user to browse, read metadata and grant access to secrets in a specific environment.

Manage secret groups:: Enables a user to create, modify, delete, read, and clone secret groups in a specific environment, as well to check if the user can initiate a new clone or restore operation.

Read secrets metadata:: Enables a user to browse and read metadata of secrets in a specific environment.

Write secrets:: Enables a user to upload, create, modify secrets in a specific environment.

////
== Tokenization

Where did this go?...not in QAX

Manage Tokenization Services:: ?

Manage Tokenization Formats:: ?
////

== Usage

Usage Viewer:: Enables a user to view usage reports.

== Visualizer

Visualizer Editor:: Enables a user to view, create, modify, and delete content in Anypoint Visualizer.
