= Permissions Available in Anypoint Platform
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The following permissions can be assigned to xref:teams.adoc[teams], granted to xref:users.adoc#grant-user-permissions[individual users], or combined to xref:roles.adoc#create-custom-roles[create custom roles].

== Access Management

[%header%autowidth.spread]
|===
| Permission | Description
| Organization Administrator
a| 
* At the root organization level, grants a user most permissions available in Anypoint Platform, including but not limited to secrets management, network administration, and other view, modify, execute, and delete permission.

* On the Organization Administration page, enables a user to:

** Add and manage users and permissions.
** View and edit organization details.
** Access API Manager client applications.
** Access the client ID and client secret for the organization.
** Customize the theme of the developer portal.
* Enables a user to edit all versions of all APIS, registered applications, and API portals in Anypoint Platform.

For security reasons, distribute this permission to as few users as possible.

| Audit Log Config Manager
a|
Enables a user to configure the retention period for audit logs over their organization.

This permission must be applied at the root organization level. It appears only if the organization has the modern UI enabled in Access Management.
| Audit Log Viewer
a| Enables a user to view audit logs in Access Management.
|===

== DataGraph

[%header%autowidth.spread]
|===
| Permission | Descrption
| Contribute 
a| 
Enables a user to:

* Add source APIs to the unified schema.
* Edit any source API schema added to the unified schema. 
* Request access to run queries.
* Promote API schemas to an environment.
* View query traces in real time while running queries from the UI.
* Download a copy of the unified schema from the query editor.
| Consume 
a| 
Enables a user to:

* View and explore the unified schema.
* Request access to run queries and make data requests from the UI.
* Download a copy of the unified schema from the query editor.
| Operate
a|
Enables a user to:

* View customer-facing logs.
* Set a dedicated load balancer URL for Anypoint Datagraph.
|===
