= Switch from Roles to Teams
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Roles feature will be replaced by Teams after 6 months after general availability (GA). You must transition your legacy roles to the new Teams feature to get all of the benefits of the Teams feature.  Legacy roles are available within the business group view.

For every role that is defined by Anypoint Platform, a corresponding permission is available. If you use custom roles, you may need to assign multiple permissions to recreate the custom role. For more information on available permissions in Anypoint Platform, see xref:permissions-by-product.adoc[Permissions by Product].

// To switch from Roles to Teams:

// . In *Access Management*, select <page>.
// . In the banner on the <page> page, select *Learn More*.
// . Select *Get Started*.
// . ...etc

== Switch from Teams to Roles

Before the Roles feature reaches end of life, you can switch your organization’s permissions structure from the Teams structure back to the Roles structure.

[WARNING]
Using the Roles feature should be a temporary measure as you finalize the optimal team structure for your organization. The Roles feature will be unavailable 6 months after the Teams feature is introducted. When the Roles feature is no longer available, your organization is adopts the Teams structure automatically. To ensure there are no lapses in user permissions, we recommend keeping the Teams feature as your primary permissions structure.

// To switch from Teams to Roles:

// . tbd
