= Configure Single Logout
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

As Administrator, you can configure single logout if you use SAML. OpenID Connect does not support single logout. Using single logout, a user or user agent can log out of an authenticated environment and ensure that both service providers and identity servers process the logout correctly.

This procedure shows how to perform single logout and how to control where the user is redirected after signing out. Redirecting the user to a different page is often preferred. You can configure such a redirect in your PingFederate configuration. You can add a `redirect_uri` query parameter to the SLO Service URL, and Anypoint Platform routes the user there rather than to the Anypoint Platform sign-in page.

. In PingFederate, for example, click the SP Configuration for the Anypoint Platform.
. In *Browser SSO > Configure Browser SSO > SAML Profiles*, ensure that these fields are set:
+
* IdP-Initiated SSO
* IdP-Initiated SLO
* SP-Initiated SLO
+
. In *Protocol Settings > Configure Protocol Settings*, configure a SLO Service URL with the following values:
+
* Binding: POST
* Endpoint URL
+
Set `PARTNER_SP_ID` to the correct value: `+https://anypoint.mulesoft.com/accounts/logout/receive-id+`
+
. Redirect users to your sign-in page using the following URL:
+
----
https://anypoint.mulesoft.com/accounts/logout/receive-id?redirect_uri=https%3A%2F%2Fanypoint.mulesoft.com%2Faccounts%2Flogin%2Fyour-domain
----
+
Alternatively, redirect users to your portal page using the following URL:
+
----
https://anypoint.mulesoft.com/accounts/logout/receive-id?redirect_uri=https%3A%2F%2Fanypoint.mulesoft.com%2Fapiplatform%2Fyour-domain%2F%23%2Fportals
----
+
. In *Allowable SAML Bindings*, click *Redirect*.
. In *Encryption Policy*, make sure nothing is encrypted, then save and exit Protocol Settings and Browser SSO.
. When viewing the SP Configuration for Anypoint Platform, go to *Credentials > Configure Credentials*.
. Set *Signature Verification Settings > Manage Signature Verification Settings > Trust Model to Unanchored*, and import the certificate from the following location:
+
`+http://docs.mulesoft.com/downloads/access-management/anypoint-platform-slo.pem+`
+
. Make this certificate the active certificate.

== See Also

* xref:managing-users.adoc[Configure SAML for SSO]