= Manage User Access Using Teams

Use the Teams feature to create groups of users and then assign the members of those groups selected permissions. Teams have a cascading permissions structure so managing users and permissions is scalable.

If you have the Organization Administrator permission in the root organization, you can:

* Manage your organization from a simple, global view.
* Group users into teams to easily manage permissions and share assets.
* Assign team maintainers to delegate management of team members and child teams.
* Manage user and team permissions across multiple business groups in one place.

Starting with the “Everyone at <Root Organization>" team, which contains all users who join your organization either via an invitation or SSO, you can create specialized _child teams_ that have more specific permissions based on the responsibilities of their members.
The Teams feature enables you to mimic the structure of your organization and seamlessly manage permissions and team membership as your organization grows.

After your child teams are created, you can invite new users directly to the appropriate team using email invitations or using the xref:configure-teams#invite-users-with-teams[Teams feature interface].

When you add a user to a team, you can also specify whether they should be a _team maintainer_ (a user who receives the permissions outlined in the team structure and manages team membership) or a _member_ (a user who receives the permissions outlined in the team structure). Outside of teams, you can still xref:users.adoc#grant-user-permissions[assign specific permissions to individual users] if they require permissions that should not extend to an entire team.

Adopting a team structure in your organization also enables you to share assets more easily. In Anypoint Exchange, you can share an asset with an entire team rather than having to select each user individually.

[NOTE]
To manage teams permissions, you must have the Organization Administrator permission in the business group that contains the resources you want to give a specific user or team access to.
To modify permissions for all the teams in the organization, you must be a root organization administrator.

== Permissions Structure

When you're planning your organization’s team structure, keep in mind that:

* Each member of your organization is a member of the “Everyone at <Root Organization>" team, or the _root_ team. For security, when you configure permissions in your organization, give your organization’s root team “Everyone at <Root Organization>" only permissions you want every user in the organization to have.
* Your team structure should reflect the structure of your organization so that you can plan your teams and configure permissions according to member needs. 
* You can move teams if the needs of your organization change.
* Teams names must be unique across your organization.
* Your organization can have up to 1000 teams.
* Your can nest teams up to 10 levels, including the “Everyone at <Root Organization>" team.
* You can create teams without adding members.
* Every child team inherits permissions from its parent team. You can give each child team more specialized permissions that reflect the team members’ responsibilities.

Each team has a _team maintainer_, a member who can add new users to their own team. A team maintainer can only assign members to their specific team or child teams. Team maintainers can also designate new maintainers for teams they manage. If you are the organization administrator of the root organization, you can add users as members or maintainers to any team in the organization. 

For an example of a teams structure applied across an organization, see xref:teams-example.adoc[Example Teams Structure].

== Opt in to Teams

// I don't think this is accurate. Need to test.

include::partial$include-nav-steps-no-permissions.adoc[]

. In the Access Management navigation menu, click *Try New Features*.
. Click *Start Using These Features*. 
+
The Access Management navigation menu options change so you can use the Teams feature. You can xref:configure-teams.adoc#create-a-child-team[create a team] or xref:roles.adoc#migrate-roles-to-teams[migrate existing roles and permissions to teams].

== Grant Permissions to Individual Users

If you have the Organization Administrator permission, you can assign permissions to individual users without assigning those users to a team. For more information about assigning permissions to individuals, see xref:users.adoc#grant-user-permissions[Grant Permissions and Roles to Users].

== See Also

* xref:configure-teams.adoc[Configure Teams]
* xref:teams-example.adoc[Example Teams Structure]
* xref:users.adoc#inviting-a-user-to-anypoint-platform[Inviting a User to Anypoint Platform]
* xref:users.adoc#grant-user-permissions[Grant Permissions and Roles to Users]
* xref:map-users-roles-teams.adoc[Map SSO Users to Teams]
