= Anypoint Platform Access FAQs
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: anypoint platform, permissions, configuring, limits

[[access-IAM]]
== Access and Administration

For complete information on user permissions, see xref:permissions-by-product.adoc[Permissions Available in Anypoint Platform].

=== Who can access Access Management?

Users who have the Organization Administrator permission over their root organization or business group have view and edit permissions in Access Management.

Users who are team maintainers can also access Access Management, although their actions within Access Management vary based on their other permissions.

=== Who can access audit logs?

Users who have the Audit Log Viewer permission can view audit logs in Access Management even if they lack administrator permissions. For more information, see the xref:audit-logging.adoc#access-audit-logging[audit logs documentation].

=== Who can modify connected apps?

Only users who have the Organization Administrator permission over the root organization can view and edit connected apps. Users with administrative permissions over business groups (and not the root organization) cannot view or edit connected apps.

Some features in Access Management cannot be accessed using any connected app scopes or permissions. These features are available only using the user interface on the web or using a bearer token generated by an authenticated user who has the Organization Administrator permission over their root organization. For more information, see the xref:connected-apps-overview.adoc#access-and-authorization[connected apps documentation].

[[access-management-limits]]
== Limits

Access Management imposes the following limits on features in an organization:

=== Organization limits:

* Business groups per root organization: 100
* Users per root organization: 10,000
* Environments per root organization or business group: 150
* API Manager clients per root organization
** Managed by Anypoint Platform's internal client provider: 10,000
** Managed by external client providers: 10,000
* External access relations per root organization: 20
* Permissions per external organization: 1000
* Audit log retention period: Between 30 and 2190 days

=== Teams, roles, and user permissions:

* Teams per root organization: 1000
* Levels nested under parent teams: 10
* Permissions per team: 1000
* Permissions per API Manager client or runtime client: 3000
* Permissions per custom role: 400
* Permissions per user: 5000
* Roles per root organization or business group: 500
* Roles per user: 700
* External group mappings per team: 100

=== Identity providers:

* Identity management provider keys per provider: 3
* Identity management providers per root organization: 25

=== Client providers:

* Client management providers per root organization: 25

=== Connected apps:

* Authorized applications per user: 30
* Connected apps accessible by external organizations: 20
* Connected apps per root organization: 2000
* Scope assignments per connected application: 1000

=== User Token Limits:

* Active tokens per user in Gov Cloud: 100
* Active tokens per user in EU Region: 100


== Accounts

=== Can I create multiple accounts with one email address?

You can create multiple accounts using the same email address, whether the accounts belong in one organization or in different organizations. Your username must be unique for each account.

=== How do I join an existing organization?

To join an existing organization, contact an Organization Administrator for the organization that you need to join and ask them to send you an invitation to that organization.
Once you receive your invitation, you can create a new account to accept the invitation and associate your account with the organization.
[NOTE]
Any data that you entered into an organization from an account that you created yourself remains associated with the old organization.

=== How do I find billing information for my account?

Talk your account representative, or use https://www.mulesoft.com/contact[the MuleSoft contact form] to obtain billing information.

=== What can I do if my trial is about to expire?

Talk to your account representative or use https://www.mulesoft.com/contact[the MuleSoft contact form] to request an Enterprise license for your on-premises Mule Runtime instances or to create a subscription account on CloudHub.

=== Where do I log in with external identity management?

If your organization uses external identity management, log into your account at *anypoint.mulesoft.com/accounts/login/_yourorganizationname_*.

=== How do I delete my account?

Please create a https://help.mulesoft.com[MuleSoft support case] for account deletion or migration.

== Account Invitations

=== What account should I use?

If you have one or more existing MuleSoft community accounts tied to the email address at which you received your invitation, MuleSoft prompts you to use your existing account to log in and accept the invitation. You can also choose to create a new account by following the *Sign Up* link at the bottom of the form.

=== How can I use a different email address?

Accept the invitation using the email where it was sent. After you've accepted the invitation, visit your profile to change your email address.

=== Why can't I see anything?

If you accept an invitation, log in, and can't see anything on your organization's Developer Portal, one of the following might be affecting your view:

* No one in your organization has added any APIs yet, and thus there are no API Portals to display.
* You haven't been granted *Portal Viewer* access to any private API Portals, and there are no public API Portals to display.

== API Access

=== How do I grant access to my API Version?

To give others access to your API Version, you must be the *API Version Owner*, and they must be a member of your organization.

. Navigate to your API Version Details page.
. Click the *Permissions* tab.
. Invite a user to access your API, if that user is a member of the same organization as you.
. Once you add a user, you can manage *Portal Viewer* access or *API Version Owner* access using the drop-down in the *Permission* column. This tab also enables you to view all users who have been granted direct permissions to your API.
[NOTE]
The *Permissions* tab doesn't display any users with permissions based on a custom role because roles can't be managed from API Version Details pages. Contact your *Organization Administrator* for information about role-based permissions to your API version.

=== How do I browse Developer Portals?

Sign out of your account to browse Developer Portals for other organizations. While you are logged into your own organization, you can access only your own organization's Developer Portal.
[NOTE]
To request access to an API that belongs to a different organization, you need to have an Anypoint Platform account for that organization.

=== How can I request access to an API?

If you're not a member of the organization that owns an API that you want to use:

* Log in using an account in the organization that owns the API.
* If you don't have an account with the organization, review the documentation in the API Portal for information about how to request an account.

=== See Also

* xref:troubleshoot-access-management.adoc[Troubleshoot Access Management]
* xref:permissions-by-product.adoc[Permissions by Product]
* xref:audit-logging.adoc#access-audit-logging[Access Audit Logs]
* xref:connected-apps-overview.adoc#access-and-authorization[Connected Apps Access and Authorization]
