= Troubleshoot Access Management
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

These tips provide information on what to do if you encounter issues.

== Problems with Accessing Anypoint Platform

=== Sign in Credentials are Not Recognized

If your credentials aren't recognized when you try to sign in to Anypoint Platform, try the following:

* Check that you are using the correct URL to sign in to your organization. +
If your organization uses an external identity management system, your signin URL is *anypoint.mulesoft.com/accounts/login/_yourOrganizationDomain_*.
* Verify that you are using the correct username and password for the account.
* If your organization isn't using an external identity management system and your signin credentials aren't working, reset your password or ask your Organization Administrator if your account is still active.

=== Access Management Invitation Link Returns an Error

If you click the link in your invitation and an error is returned, your invitation may have expired or been rescinded. Please contact your Organization Administrator for a new invitation.

== OpenID Connect Client Management

=== Error received when you try to update a client application

If you receive an `There was an error while talking to CoreServices` when you try to update a client application under OpenID Connect management, this is because updates of clients created through this integration are not currently supported.

See xref:configure-client-management-openid-task.adoc[Configure OpenID Connect Client Management]

=== Error Received When Doing a Redirect

When a redirect to the OpenID Connect Provider occurs, you receive an `Invalid Scopes error`.

Cause: This can happen if the `openid`, `profile`, and `email` scopes aren't supported by the auto-registered client.

Solution: Add the `openid`, `profile`, and `email` scopes to the client manually.
