= Add Salesforce Organizations to Your Anypoint Platform Organization

Establish a connection between your Anypoint Platform organization and a trusted Salesforce organization (tenant) to enable the management of Anypoint Platform features from the Salesforce organization. You can establish relationships with multiple Salesforce organizations in your Anypoint Platform organization, but a Salesforce organization can be connected to only one Anypoint Platform organization.

When you connect an Anypoint Platform organization with a Salesforce organization, a Saleforce admin can: 
////
* Access a catalog of APIs hosted by Anypoint Platform that can then be instantiated as invocable actions in their Salesforce organization. 
* Enable the Einstein feature for the connected Anypoint Platform organization from within the Salesforce user interface. After the Salesforce admin enables Einstein, the Anypoint Platform organization is aware that the feature is enabled and the Anypoint organization is then enabled as a target for Einstein integrations with Anypoint Platform features. 
////
* Enable invocable actions so that MuleSoft developers can publish invocable actions directly from their Robotic Process Automations (RPA) and Composer flows.

When a Salesforce organization establishes a tenant relationship with an Anypoint Platform organization, an Anypoint Platform user with the Organization Administrator permission can then enable or disable this relationship in *Access Management*. 

For more information about initiating and maintaining a relationship with Salesforce, see https://help.salesforce.com/s/articleView?id=sf.external_services_manage_your_mulesoft_anypoint_platform_connection.htm&type=5[Manage Your MuleSoft Anypoint Platform Connection] in the Salesforce documentation.

The connection between your Anypoint Platform and Salesforce organizations is managed in both Anypoint Platform access management by the Anypoint Platform Organization Administrator and the Salesforce organization by the Salesforce admin in the *MuleSoft > Setup* page. 

Use the Salesforce *MuleSoft Anypoint > Setup* user interface to:

* Initiate and complete the connection process to your Anypoint Platform organization.
* Disconnect or reconnect an Anypoint Platform and Salesforce organization.
* Delete the connection between your Anypoint Platform organization and your Salesforce organization.

Use the Anypoint Platform *Access Management > Salesforce* user interface to:

* Add connections to Salesforce organizations
* Continue creating a connection to a Salesforce organization.
* Enable or disable a tenant relationship with Salesforce.
* Delete the relationship between Anypoint Platform and a Salesforce organization.
* Manage connected Salesforce organizations.

== Before You Begin

You must have the following:

* The Anypoint Platform Organization Administrator permission at the root organization level
* Salesforce admin permission set
* Any permissions required to modify Salesforce connections
* The tenant key of the Salesforce organization to connect
* The Anypoint Platform organization ID

[connect-orgs]
== Connecting With a Salesforce Org in Anypoint Platform

As an Anypoint Platform root organization administrator, you can create  a ou must have the Salesforce organization tenant key to connect before you can connect to a Salesforce organization. If you don't have the Salesforce organization tenant key, contact the Salesforce admin for the organization to connect. 

include::partial$include-nav-steps-org-admin.adoc[]

. Click *Salesforce*.
. Click *Add Salesforce Org*.
. Enter the Salesforce organization tenant key, and click *Confirm*. 
The format for the Salesforce tenant key is `cloud/env/org-id`.
. In the *Add the Salesforce Org* dialog, click *Add*. 
. Click *Copy* to copy the Anypoint Platform ID. 
. If you are the admin for the Salesforce org you are adding, click *Manage in Salesforce* to continue setting up the relationship. 
+
If you are not the Salesforce organization administrator, provide the Anypoint Platform organization ID to the Salesforce administrator.

The Salesforce organization appears in the *Salesforce Orgs* section with the `Disabled` status.

[complete-organization-connection]
== Completing the Organization Connection in Salesforce

To complete connecting your Anypoint Platform organization to a Salesforce organization:

include::partial$include-salesforce-mulesoft-setup-nav.adoc[]

. In the *Your connected Anypoint Platform Organization* section, click *View Connection Info*.
. In the *Connection to MuleSoft Anypoint Platform* dialog, enter your Anypoint Platform organization ID in the box, and then click *Connect*.
+ 
You are returned to the *Connection to MuleSoft Anypoint Platform* page and see the details of the connected Anypoint Platform organization. 

[enable-disable-connection]
== Enabling or Disabling a Connection in Anypoint Platform

When you enable the connection with a Salesforce organization, you can publish assets from your Anypoint Platform organization to the trusted Salesforce organization. When you disable the connection, the Salesforce organization still appears in the list of available organizations but you can no longer publish assets from your Anypoint Platform to your Salesforce organization. Disabling a connection does not sever the connection to your Salesforce organization. 

include::partial$include-nav-steps-org-admin.adoc[]

. Click *Salesforce*.
+
If your organization has at least one established tenant relationship, a list of Salesforce organizations appears, showing the name, organization ID, and status of the relationship connection.
. Click *Enable* or *Disable* for the Salesforce org you want to enable or disable the connection for.

[removing-connection]
== Removing a Connection in Salesforce

You can remove the connection between your Anypoint Platform organization and your Salesforce organization using the Salesforce user interface. After you remove the connection, administrators with the appropriate permissions in both your Anypoint Platform and Salesforce organizations must recreate the connection if they want to reestablish a relationship.

include::partial$include-salesforce-mulesoft-setup-nav.adoc[]

. In the *Your connected Anypoint Platform Organization* section, click *View Connection Info*.
. In the *Go To Anypoint* drop-down list, select *Remove connection.*
. In the *Remove connection to Anypoint Platform* dialog box, click *OK*.

Alternatively, if you want to temporarily prevent Anypoint Platform users from publishing assets to Salesforce from the Anypoint Platform side, you can instead <<enable-disable-connection,disable>> the connection temporarily.

For more information about managing this relationship from the Salesforce user interface, see the https://help.salesforce.com/s/articleView?id=sf.external_services_manage_your_mulesoft_anypoint_platform_connection.htm&type=5[Salesforce documentation]. 


== See Also

* xref:manage-capabilities.adoc[]
* xref:manage-connected-salesforce.org[]


