= Establish a Tenant Relationship to a Trusted Salesforce Organizations 

Salesforce organizations can establish a tenant relationship with Anypoint Platform organizations. After establishing this relationship, an Anypoint Platform user with the Organization Administrator permission can enable or disable this relationship in *Access Management*. You can also disconnect Anypoint Platform from Salesforce at any time. For more information about initiating and maintaining a relationship with Salesforce, see https://help.salesforce.com/s/articleView?id=sf.external_services_manage_your_mulesoft_anypoint_platform_connection.htm&type=5[Manage Your MuleSoft Anypoint Platform Connection] in the Salesforce documentation.

Using the Salesforce user interface, you can:

* Initiate and complete the connection process to your Anypoint Platform organization.
* Disconnect or reconnect your Anypoint Platform organization from your Salesforce organization.
* Delete the connection between your Anypoint Platform organization and your Salesforce organization.

Using the Anypoint Platform user interface, you can:

* Continue creating a connection to a Salesforce organization.
* Enable or disable a tenant relationship with Salesforce.

== Before You Begin

You need the following:

* The Organization Administrator permission at the root organization level in Anypoint Platform
* Any permissions required to modify Salesforce connections
* A connection code from your Salesforce organization

== Create a Connection

To initiate the connection creation process, you need the connection code from your Salesforce organization.

include::partial$include-nav-steps-org-admin.adoc[]

. Click *External Access*.
. In the *External Access* page, click *Salesforce*.
. Click *Connect with a new Salesforce Org*.
. Enter your connection code from your Salesforce organization.
. Click *Confirm*. +
After the connection completes on the Anypoint Platform side, a connection code for your Anypoint Platform organization appears.
+
. Copy the Anypoint Platform connection code.
. Return to the Salesforce connection creation interface, and enter your Anypoint Platform connection code.
. Complete the instructions in Salesforce.

The successful tenant relationship appears in the *Salesforce* section of *External Access* with the `Enabled` status.

== Disconnect or Reconnect an Existing Connection

If you want to sever the connection from your Salesforce organization to your Anypoint Platform organization, you can disconnect your Anypoint Platform organization using the Salesforce user interface. If you want to resume publishing assets from Anypoint Platform to Salesforce after you disconnect the Salesforce organization, you must reconnect the organizations. 

Alternatively, if you want to temporarily prevent Anypoint Platform users from publishing assets to Salesforce from the Anypoint Platform side, you can instead disable the connection temporarily.

For more information about managing this relationship from the Salesforce user interface, see the https://help.salesforce.com/s/articleView?id=sf.external_services_manage_your_mulesoft_anypoint_platform_connection.htm&type=5[Salesforce documentation]. 

== Enable or Disable a Connection to Your Organization

When you enable the connection with your Salesforce organization, you can publish assets from your Anypoint Platform organization to the trusted Salesforce organization. When you disable the connection, the Salesforce organization still appears in the list of available organizations but you can no longer publish assets from your Anypoint Platform to your Salesforce organization. Disabling a connection does not sever the connection to your Salesforce organization. 

include::partial$include-nav-steps-org-admin.adoc[]

. Click *External Access*.
. In the *External Access* page, click *Salesforce*. +
If your organization has at least one established tenant relationship, a list of Salesforce organizations appears, showing the name, organization ID, domain, and status of the relationship connection.
+
. Click *Enable* or *Disable*.
