= Salesforce Organization Connections in Anypoint Platform

Enable cross-platform features between your Anypoint Platform organization and a trusted Salesforce organization (tenant) by establishing a connection between them. 

After you establish a tenant relationship between your Anypoint Platform organization and a Salesforce organization, users in your organization can:

* Enable API Catalog to view and sync MuleSoft APIs and MCP servers available in the connected Salesforce organization.
* Enable generative AI capabilities in Anypoint Code Builder, Anypoint Exchange, and Intelligent Document Processing (IDP).
* Enable MuleSoft Direct so Salesforce administrators can discover and deploy pre-built integrations directly from the connected Salesforce organization.
* Enable Integration Intelligence to use AI-powered insights for monitoring, analysis, and troubleshooting of MuleSoft integrations.

When you establish the tenant relationship, you can initiate, complete, and manage the tenant relationships. You can also enable, disable, and remove connections. 

You can establish relationships with multiple Salesforce orgs in your Anypoint Platform organization, but a Salesforce organization can connect to only one Anypoint Platform organization.

== Anypoint Platform Administrators

Anypoint Platform organization administrators can:

* Initiate the connection process to a Salesforce organization.
* Enable a tenant relationship with Salesforce.
* Remove the relationship between Anypoint Platform and a Salesforce organization.
* Manage connected Salesforce organizations.

== Salesforce Organization Administrators

Salesforce admins can: 

* Complete the connection process to the Anypoint Platform organization.
* Disconnect or reconnect an Anypoint Platform and Salesforce organization.
* Remove the connection between the Anypoint Platform organization and the Salesforce organization.
* Enable the connected Anypoint Platform organization to use the Salesforce organization's Einstein generative AI capability.
 
For more information about initiating and maintaining a relationship with a Salesforce organization, see https://help.salesforce.com/s/articleView?id=platform.mulesoft_manage_your_anypoint_platform_connection.htm&type=5[Manage Your MuleSoft Anypoint Platform Connections] in Salesforce Help.


== See Also
* xref:connecting-salesforce-orgs.adoc[]
* xref:managing-connected-salesforce-orgs.adoc[]
* xref:manage-capabilities.adoc[]
