= Trusted Salesforce Organizations

Enable cross-platform features between your Anypoint Platform organization and a trusted Salesforce organization (tenant) by establishing a connection between them. 

Establishing a tenant relationship between an Anypoint Platform organization and a Salesforce organization enables users in your organization to:

* Enable API Catalog to import managed MuleSoft APIs into Salesforce, view a catalog of MuleSoft APIs that are available for use in Salesforce, and sync APIs to get the latest changes and updates.
* Publish invocable actions directly from their Robotic Process Automations (RPA) and Composer flows.
* Enhance Anypoint Code Builder and Intelligent Document Processing (IDP) developer experiences with Einstein. 

When you establish the tenant relationship, you can initiate, complete, and manage the tenant relationships. You can also enable, disable, and remove connections. 

You can establish relationships with multiple Salesforce orgs in your Anypoint Platform organization, but a Salesforce organization can connect to only one Anypoint Platform organization.

== Anypoint Platform Administrators

Anypoint Platform organization administrators can:

* Initiate the connection process to a Salesforce organization.
* Enable a tenant relationship with Salesforce.
* Remove the relationship between Anypoint Platform and a Salesforce organization.
* Manage connected Salesforce organizations.

== Salesforce Organization Administrators

Salesforce admins can: 

* Complete the connection process to the Anypoint Platform organization.
* Disconnect or reconnect an Anypoint Platform and Salesforce organization.
* Remove the connection between the Anypoint Platform organization and the Salesforce organization.
* Enable Anypoint Platform automation developers to publish invocable actions directly from their Robotic Process Automations (RPA) and Composer flows. 
* Enable the connected Anypoint Platform organization to use the Salesforce organization's Einstein capability.
 
For more information about initiating and maintaining a relationship with a Salesforce organization, see https://help.salesforce.com/s/articleView?id=sf.external_services_manage_your_mulesoft_anypoint_platform_connection.htm&type=5[Manage Your MuleSoft Anypoint Platform Connection] in the Salesforce documentation.


== See Also
* xref:connecting-salesforce-orgs.adoc[]
* xref:managing-connected-salesforce-orgs.adoc[]
* xref:manage-capabilities.adoc[]



