= Unified Identity Management

Unified identity management provides a Salesforce Home org, a single place to create and manage users. The Salesforce Home org simplifies user management and reduces redundancy as users have only one user ID across both Salesforce and Anypoint Platform. All forms of authentication are managed in the Salesforce Home Org.

All users are created and maintained in the Salesforce Home org. Users in the Salesforce Home org who are assigned MuleSoft permissions only need to log in to their Salesforce Home org to seamlessly navigate to the connected Anypoint Platform org to use Anypoint Platform features. 

Unified identity management ensures a seamless user experience, eliminates the need for multiple user accounts, and enhances security by centralizing identity management in the Salesforce Home org. 

Anypoint Platform-specific permissions are managed in Anypoint Platform. 

== Before you Begin

You must have the MuleSoft Integration license for your Salesforce org.


== See Also

* xref:permissions-by-product.adoc[]





