= Update Your User Profile
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Update your Anypoint Platform user profile information automatically by signing in via your configured external identity provider (IdP). Understand how Anypoint Platform maps claims like `preferred_username`, `email`, and `sub` from the IdP to create or update your profile details. Subsequent logins through the IdP will refresh your profile with the latest information provided by the IdP.

Your user profile includes a username, your name, and email address. Typically, the OpenID Connect `userinfo` endpoint provides a `preferred_username` claim that contains the authenticated user’s username. However, some IdPs such as OpenAM and PingFederate do not support the `preferred_username` claim. Therefore, when Anypoint Platform creates a user, the `email` and `sub` claim values comprise the username if the `preferred_username` claim isn't present.
Claims are made in the following order: `preferred_username`, `email`, `sub`. If a username is created as a single string of random characters and does not have an email address defined, the string may be returning the `sub` claim that the `id` token and `userinfo` endpoint show for the user. 

To update user profile information from your configured IdP, sign in to Anypoint Platform through the IdP. When you sign in, your user profile is automatically updated with the information from the IdP.
