= Users
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

As an administrator of your root organization, you can enable, disable, or delete users.

By selecting the checkbox next to a user, additional options related to that user are displayed:

* *Enable*: Enables the user in the selected organization or business group.
* *Disable*: Disables the user in the selected organization or business group. They are no longer able to log in.
* *Delete*: When deleting from the top level Organization, all of the user's roles/permissions are removed and the user becomes unattached. When deleting from a business group, all of the user's roles/permissions for only the selected business group are removed.

== Before You Begin

Before getting started, ensure that you have:

* The Organization Administrator permission
* The API Version Owner permission if you plan to manage user permissions for your API version

== Inviting a User to Anypoint Platform

[NOTE]
--
This feature is not available in Anypoint Platform Private Cloud Edition.

When running Anypoint Platform Private Cloud Edition, you need to configure user management methods such as SSO through a third-party IdP or LDAP.
--

As an organization administrator of a root organization or of one of its business groups, you can invite new users and manage existing users for your organization.

To invite new users to your organization:

include::partial$include-task-grant-user-permissions.adoc[tags=navUsers]

. Click *Invite user*.
. Enter the email addresses of the users that you want to invite to your organization as a comma-separated list.
. Optionally, select a xref:teams.adoc[team] or xref:roles.adoc[role (deprecated)] for assign these users.
. Click *Send Invitation*.

The users you specify receive email invitations to join your organization. Invited users must use the link they receive in the invitation to join your organization. When they click the link, they are presented with a sign-up form that already has the *Company* field completed with the name of your organization.

Note that the email link expires in one week.

Invited users have access to the same set of resources as you (although they may have different permissions that can restrict what they can view or do).

== Resending or Canceling a Sent Invitation

Click *Pending Invites* to view all invitations that have not yet been accepted. Select the ones you need to manage, and click *Re-send Invite* or *Cancel Invite*.

[[grant-user-permissions]]
include::partial$include-task-grant-user-permissions.adoc[leveloffset=+1,tags=description;navStepsOrgAdmin;finalSteps]

== Managing External Users of Your Public APIs

When you make an API portal public, users from any other Anypoint Platform organization can register client applications to call your API. When these users log in to your public developer portal, they are considered external users because they are outside of your organization.

When a user logs into Anypoint Platform for the first time, they are automatically added to the *External Users* tab. From the *External Users* tab in Access management, you can view a list of all external users. You can also enable or disable each of these external users from this screen. When you disable an external user, they can no longer log in to your public portal.

You cannot search for external users in other parts of Anypoint Platform because these users do not belong to your organization and do not have additional permissions. To grant users permission to perform tasks like deploying an application, you must invite the user to join your organization.



== See Also

* xref:exchange::to-share-an-asset.adoc[To Share an Asset or Publish to a Portal]
* xref:external-identity.adoc#managing-users[user management]
* xref:external-identity.adoc#instructions-for-saml-configuration[SSO through a Third-party IdP]
* xref:external-identity.adoc#configure-ldap[LDAP]
