= Users
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

As an administrator of your root organization, you can enable, disable, or delete users.

By selecting the checkbox next to a user, additional options related to that user appear:

* *Enable*: Enables the user in the selected organization or business group.
* *Disable*: Disables the user in the selected organization or business group. They are no longer able to log in.
* *Delete*: When deleting from the root organization, all of the user's permissions are removed, and the user becomes unattached. When deleting from a business group, all of the user's permissions for only the selected business group are removed. The deleted user's data resides in the organization for audit logging purposes.

== Before You Begin

Before getting started, ensure that you have:

* The Organization Administrator permission
* The API Version Owner permission if you plan to manage user permissions for your API version

== Inviting a User to Anypoint Platform

[NOTE]
--
This feature is not available in Anypoint Platform Private Cloud Edition, Government Cloud or for organizations that use external identity providers for single sign-on (SSO). You must manage users, including invitations for new users, through your third-party IdP or LDAP.
--

As an organization administrator of a root organization or of one of its business groups, you can invite new users and manage existing users for your organization.

To invite new users to your organization:

include::partial$include-nav-users.adoc[]

. Click *Invite user*.
. Enter the email addresses of the users that you want to invite to your organization as a comma-separated list.
. Optionally, select a xref:teams.adoc[team] or xref:roles.adoc[role (deprecated)] to assign permissions to these users.
. Click *Send Invitation*.

The users you specify receive email invitations to join your organization. Invited users must use the link they receive in the invitation to join your organization. When they click the link, they are presented with a sign-up form that already has the *Company* field completed with the name of your organization.

Note that the email link expires in one week.

Invited users have access to the same set of resources as you (although they may have different permissions that can restrict what they can view or do).

== Resending or Canceling a Sent Invitation

Click *Pending Invites* to view all invitations that have not yet been accepted. Select the ones you need to manage, and click *Re-send Invite* or *Cancel Invite*.

[[grant-user-permissions]]
== Grant Permissions to Users

Organization administrators manage user access using xref:teams.adoc[teams] or xref:roles.adoc[roles] (deprecated), or by granting permissions to users individually. Note that teams and roles functionality are mutually exclusive.

In the *Users* page, click a user name to access more information about that user, manage and view permissions, manage and view teams or roles, or reset their password.

By default, in every new organization and business group, you can assign the following:

* Assign API permissions: Write the name of the API you want to give access to, then pick a version and permission.
* Assign Runtime Manager permissions: Write the name of the Runtime Manager environment to give access to, then pick a permission.
* Assign teams: Write the name of the team to give access to.
* Assign roles (deprecated): Write the name of the role to grant. Check the xref:roles.adoc[roles] section for a description of the default roles within an organization and business group.

[NOTE]
--
In the legacy roles user interface, roles and permissions are grouped under organizations (and also, optionally, under business groups). This means that you can only assign roles and permissions that are related to resources that exist in the organization and/or business group that you are selecting.
--

If necessary, you can also remove user permissions, but note that if those permissions are granted through an assigned team or role, you can remove them only by using the xref:teams.adoc[teams] or xref:roles.adoc[Roles] functionality respectively. You cannot view or remove team-based or role-based permissions in the *Users* page.

Because the Roles feature is deprecated, it is best to xref:teams.adoc#opt-in-to-teams[opt in to the Teams feature] to manage permissions in a hierarchy.

To grant permissions to an individual user:

include::partial$include-nav-steps-org-admin.adoc[]

include::partial$include-nav-users.adoc[]

. In the *Permissions* section, click *Add permissions*.
. Next to each permission you want to grant the user, select the checkbox.
. Click *Next*.
. Select the business groups in which you want the selected permissions to apply.
. Click *Next*.
. Select the environments in which you want the selected permissions to apply.
. Review the permissions, business groups, and environments, and then click *Add permissions*.

The user now has the permissions you selected in the business groups and environments you specified.

== Managing Deleted Users

When you delete a user from your root organization, the user is _soft deleted_. This user can no longer access the root organization or business groups but maintains an Anypoint Platform account and can later be associated with another organization. Anypoint Platform maintains a record of such users for the purposes of audit logs.

If an Anypoint Platform user that was removed from an organization tries to log in to their former organization, the login request fails, with a `Your credentials are not valid` error message.

An organization administrator can invite the user to join the same organization again, but the user must create a new username. If the user tries to log in with their old account, the sign up request fails, stating `Cannot create user. User already exists`.

If a deleted federated user tries to log in, the login request fails, with a `This user is disabled` error message, but the user still appears in the organization as a disabled account. An organization administrator can re-enable this user.

== Managing External Users of Your Public APIs

When you make an API portal public, users from any other Anypoint Platform organization can register client applications to call your API. When these users log in to your public developer portal, they are considered external users because they are outside of your organization.

When a user logs into Anypoint Platform for the first time, they are automatically added to the *External Users* tab. From the *External Users* tab in Access management, you can view a list of all external users. You can also enable or disable each of these external users from this screen. When you disable an external user, they can no longer log in to your public portal.

You cannot search for external users in other parts of Anypoint Platform because these users do not belong to your organization and do not have additional permissions. To grant users permission to perform tasks like deploying an application, you must invite the user to join your organization.

== Managing Sensitive Account Information

As an organization administrator, you can modify user some sensitive user information. For enhanced security, Access Management might ask you to reauthenticate before you can modify an organization user's email address. Connected apps and clients are exempt from reauthentication. If you have a script that makes an API call to change organization users' email addresses, it might need to accommodate reauthentication.

include::partial$include-reauthentication-conditions.adoc[]

== See Also

* xref:exchange::to-share-an-asset.adoc[To Share an Asset or Publish to a Portal]
* xref:external-identity.adoc#managing-users[user management]
* xref:external-identity.adoc#instructions-for-saml-configuration[SSO through a Third-party IdP]
* xref:external-identity.adoc#configure-ldap[LDAP]
