// Used in Access Management Enabling Integration Intelligence and in Anypoint Monitoring Integration Intelligence

// tag::prereqs[]
Before enabling Integration Intelligence in your Anypoint Platform organization, you must:

* Have administrative access to an Anypoint Platform organization that isn't a trial organization and isn't expired.
* Have administrative access to a Salesforce organization that has Integration Intelligence enabled.
* xref:access-management::trusted-salesforce-org.adoc[Establish a tenant relationship] between your Anypoint Platform organization and a trusted Salesforce organization.
+
[NOTE]
====
The connected Salesforce organization must have Data Cloud and Tableau Next enabled. For more information about setting up Data Cloud, see https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/DataCloud_QuickStart_Guide.pdf[Data Cloud Quick Start Guide].

For more information about setting up Tableau Next, see https://help.salesforce.com/s/articleView?id=analytics.tua_admin.htm&type=5[Enable Tableau Next].
====
// end::prereqs[]

// tag::ii-salesforce-setup[]
The Salesforce admin sets up Integration Intelligence in the Salesforce org. 

. Log in to your Salesforce organization.
. In Salesforce Setup, enter `MuleSoft` in the *Quick Find* box, then select *MuleSoft > Integration Intelligence (Beta)*.
. Read the beta service terms and agreements, and click *Got it*.
. On the *Integration Intelligence Setup Assistant* page, follow the setup steps in order:
.. <<set-up-data-cloud,Set up Data Cloud>>
.. <<connect-with-anypoint-platform,Connect with Anypoint Platform>>
.. <<enable-telemetry-data,Enable Telemetry Data>>
.. <<enable-seamless-login,Enable Seamless Login>>
.. <<install-integration-intelligence,Install Integration Intelligence>>

// end::ii-salesforce-setup[]

// tag::set-up-data-cloud[]

. Click *Setup* to connect with Data Cloud if your org isn't already connected to a Data Cloud instance.
+
For information about setting up Data Cloud see https://help.salesforce.com/s/articleView?id=data.c360_a_set_up.htm&type=5[Set up and Maintain Data Cloud]. 
. Set up Data Cloud for Tableau Next.
+
For information about setting up Data Cloud for Tableau Next, see https://help.salesforce.com/s/articleView?id=analytics.tua_admin_setup_dc.htm&type=5[Set up Data Cloud for Tableau Next].

// end::set-up-data-cloud[]



// tag::enable-ii-in-anypoint-platform[]

An Anypoint Platform organization administrator enables seamless login for Integration Intelligence in Anypoint Platform. The Salesforce org admin must first opt in to Integration Intelligence in the Salesforce org. 

. Sign in to Anypoint Platform using an account that has the Organization Administrator permission.
. Select *Access Management* from the image:gear.svg["gear icon",20] menu.
. Select *Salesforce*.
. Enable *Ingest Telemetry Data*.
. Opt in to ingest telemetry data by selecting *I understand and agree to join the Beta program*.
. In *Initial Ingestion*, select the time period for historical data ingestion. 
. In *Business Group*, select one business group whose telemetry data will be brought to Data Cloud.
. Select *Save Settings*.

Any subsequent changes made to Integration Intelligence in Access Management (for example, disabling trust or changing business groups) are automatically shared with the connected Salesforce organization.    

// end::enable-ii-in-anypoint-platform[]

// tag::enable-telemetry-data[]


TODO_TODO

// end::enable-telemetry-data[]



// tag::enable-seamless-login[]
Seamless login lets Anypoint Platform users access Tableau Next dashboards in Salesforce without needing to create new credentials or perform additional login steps. 

// end::enable-seamless-login[]
