// tag::profileLinkingContextForUsers[]
[[profile-linking-context-users]]
= Linking Your Anypoint Platform Profiles

When you log in to an Anypoint Platform using an email address that is associated with more than one profile in the same organization, you are prompted to link your profiles together. Your options for linking profiles vary based on whether the profiles use the Anypoint identity provider (IdP) or an external IdP that uses single sign-on (SSO). Anypoint Platform supports:

* Linking an SSO profile to a local profile (login managed by Anypoint IdP)
* Linking an SSO profile to another SSO profile that uses a different IdP to log in
* Linking an SSO profile to multiple other profiles that each use different IdPs to log in

Anypoint Platform does not support linking multiple profiles that use the same IdP. You can link up to 25 user profiles.

// end::profileLinkingContextForUsers[]

// tag::profileLinkingForSSOtoLocal[]
[[sso-to-local]]
= Linking an SSO Profile to a Local Profile

When you attempt to log in using SSO and there is another user that shares the same email address but uses Anypoint Platform credentials to log in, you are prompted to link the profiles.

. In the Anypoint Platform login page, click *Sign in with <your identity provider>*.
. If prompted, enter your credentials for your IdP. +
If your SSO credentials share an email address with an profile that is managed by the Anypoint IdP, you are prompted to log in. If you are not prompted, your local profile uses a different email address than your SSO profile.
+
. In the *Link your Account* page, enter your credentials for your local Anypoint Platform profile.
. Click *Link Accounts*.
+
You can now view your linked profiles in the *Identity Providers* section of your user profile.

// end::profileLinkingForSSOtoLocal[]

// tag::profileLinkingSSOtoSSO[]
[[sso-to-sso]]
= Linking an Existing SSO Profile to Another SSO Profile

When you attempt to log in using SSO and there is another user that shares the same email address but uses a different external identity provider with SSO, you are prompted to link the profiles.

. In the Anypoint Platform login page, click *Sign in with <your identity provider>*.
. If prompted, enter your credentials for your IdP. +
If your SSO credentials share an email address with another SSO profile in the same organization, you are prompted to log in with those credentials to link your profiles. If you are not prompted, your other SSO profile uses a different email address than the SSO profile you are logging in to.
+
. In the *Link your Account* page, enter your credentials for your local Anypoint Platform profile.
. Click *Link Accounts*.
+
You can now view your linked profiles in the *Identity Providers* section of your user profile.

// end::profileLinkingSSOtoSSO[]

// tag::profileLinkingMultiple[]
[[linking-multiple-profiles]]
= Linking an existing SSO Profile to Multiple Profiles
= Linking an existing SSO Profile to Multiple Profiles
= Linking an existing SSO Profile to Multiple Profiles

When you attempt to login using SSO and there are multiple user profiles that share the same email address but use different identity providers to log in, you are prompted to link the profiles. Note that you cannot link profiles that use the same IdP.

. In the Anypoint Platform login page, click *Sign in with <your identity provider>*.
. If prompted, enter your credentials for your IdP. +
If your SSO credentials share an email address with additional profiles in the same organization, you are prompted to select one of the profiles and log in with those credentials to link your profiles. If you are not prompted, your other profiles use a different email address than the SSO profile you are logging in to.
+
. In the *Link your Account* page, select the profile you want to link. +
You can hover over each profile to see which identity provider it uses.
+
. Click *Link Accounts*.
. Enter your credentials for the profile you chose.
+
You can now view your linked profiles in the *Identity Providers* section of your user profile.


// end::profileLinkingMultiple[]

// tag::profileLinkingContextForAdmins[]
[[enable-profile-linking]]
= Enabling Users to Link Anypoint Platform Profiles

// DO NOT USE THIS SECTION YET - NOT YET SUPPORTED 

As an organization administrator, you can require users to link multiple Anypoint Platform profiles that use the same email address to log in. 

Anypoint Platform supports:

* Linking an SSO profile to a local profile (profile managed by Anypoint IdP)
* Linking an SSO profile to another SSO profile that uses a different IdP
* Linking an SSO profile to multiple other profiles that use different IdPs

Anypoint Platform does not support linking multiple profiles that use the same IdP.

include::partial$include-nav-steps-org-admin.adoc[]

include::partial$include-nav-identity-providers.adoc[]

. In the *Link Multiple Accounts* section, click *Required*. 
+
Users can no longer skip the prompt to link their user profiles when logging in to Anypoint Platform.

// end::profileLinkingContextForAdmins[]