// tag::profileLinkingContextForUsers[]
[[profile-linking-context-users]]
= Linking Your Anypoint Platform Profiles

When you log in to Anypoint Platform for the first time using an external identity provider (IdP), Anypoint Platform locates potential user accounts matched by your email address that is associated with the IdP profile. You are prompted to link your IdP profile with the existing accounts. Your options for linking profiles vary based on whether the profiles use the Anypoint identity provider (IdP) or an external IdP that uses single sign-on (SSO). Anypoint Platform supports:

* Linking an SSO login to a local profile by using credentials (login managed by Anypoint IdP)
* Linking an SSO login to another SSO login that uses a different IdP to log in
* Linking an SSO login to multiple other profiles that each use different IdPs to log in

Anypoint Platform does not support linking multiple profiles that use the same IdP. The IdP must be an OpenID Connect (OIDC) provider. You can link up to 25 user profiles. This feature is available only if an organization administrator has enabled it.

// end::profileLinkingContextForUsers[]

// tag::profileLinkingForSSOtoLocal[]
[[sso-to-local]]
= Linking an SSO Login to a Local Profile

When you attempt to log in using SSO and there is another user profile that shares the same email address but uses Anypoint Platform credentials to log in, you are prompted to link the profiles.

. In the Anypoint Platform login page, click *Sign in with <your identity provider>*.
. If prompted, enter your credentials for your IdP. +
If your SSO credentials share an email address with an profile that is managed by the Anypoint IdP, you are prompted to log in. If you are not prompted, your local profile uses a different email address than your SSO profile.
+
. In the *Link your Account* page, enter your credentials for your local Anypoint Platform profile.
. Click *Link Accounts*.
+
You can now view your linked profiles in the *Identity Providers* section of your user profile.

// end::profileLinkingForSSOtoLocal[]

// tag::profileLinkingSSOtoSSO[]
[[sso-to-sso]]
= Linking an Existing SSO Login to Another SSO Login

When you attempt to log in using SSO and there is another user that shares the same email address but uses a different external identity provider with SSO, you are prompted to link the profiles.

. In the Anypoint Platform login page, click *Sign in with <your identity provider>*.
. If prompted, enter your credentials for your IdP. +
If your SSO credentials share an email address with another SSO profile in the same organization, you are prompted to log in with those credentials to link your profiles. If you are not prompted, your other SSO profile uses a different email address than the SSO profile you are logging in to.
+
. In the *Link your Account* page, enter your credentials for your local Anypoint Platform profile.
. Click *Link Accounts*.
+
You can now view your linked profiles in the *Identity Providers* section of your user profile.

// end::profileLinkingSSOtoSSO[]

// tag::profileLinkingMultiple[]
[[linking-multiple-profiles]]
= Linking an existing SSO Login to Multiple Profiles

When you attempt to login using SSO and there are multiple user profiles that share the same email address but use different identity providers to log in, you are prompted to link the profiles. Note that you cannot link profiles that use the same IdP.

. In the Anypoint Platform login page, click *Sign in with <your identity provider>*.
. If prompted, enter your credentials for your IdP. +
If your SSO credentials share an email address with additional profiles in the same organization, you are prompted to select one of the profiles and log in with those credentials to link your profiles. If you are not prompted, your other profiles use a different email address than the SSO profile you are logging in to.
+
. In the *Link your Account* page, select the profile you want to link. +
You can hover over each profile to see which identity provider it uses.
+
. Click *Link Accounts*.
. Enter your credentials for the profile you chose.
+
You can now view your linked profiles in the *Identity Providers* section of your user profile.


// end::profileLinkingMultiple[]

// tag::profileLinkingContextForAdmins[]
[[enable-profile-linking]]
= Enabling Users to Link Anypoint Platform Profiles

As an organization administrator, you can enable users to link multiple Anypoint Platform profiles that use the same email address to log in. 

Anypoint Platform supports:

* Linking an SSO login to a local profile by using credentials (login managed by Anypoint IdP)
* Linking an SSO login to another SSO profile that uses a different IdP
* Linking an SSO login to multiple other profiles that use different IdPs

Anypoint Platform does not support linking multiple profiles that use the same IdP. Note that only OpenID Connect (OIDC) IdPs are supported.

include::partial$include-nav-steps-org-admin.adoc[]

include::partial$include-nav-identity-providers.adoc[]

. In the *Link Multiple Accounts* section, click *Enabled*. 
. Click *Save Changes*. 
+
Users in your organization can now link their SSO logins with other IdP profiles that share the same email address.

// end::profileLinkingContextForAdmins[]

// tag::requireProfileLinkingForAdmins[]

= Require Users to Link Anypoint Platform Profiles
// DO NOT USE THIS SECTION YET - NOT YET SUPPORTED 

If your organization has xref:external-identity-index.adoc#enable-profile-linking[enabled the *Link Multiple Accounts* setting], organization administrators can require all users to link available Anypoint Platform profiles.

include::partial$include-nav-steps-org-admin.adoc[]

include::partial$include-nav-identity-providers.adoc[]

. In the *Link Multiple Accounts* section, click *Required*. 
+
Users can no longer skip the prompt to link their user profiles when logging in to Anypoint Platform.

// end::requireProfileLinkingForAdmins[]
